"""Centralized column-name constants for Snowflake objects used in UI/services."""

# Shared fields
CLAIM_ID = "CLAIM_ID"
STATUS = "STATUS"
LAST_UPDATED_TS = "LAST_UPDATED_TS"
USERNAME = "USERNAME"
ASSIGNED_TO = "ASSIGNED_TO"
SECTION_ID = "SECTION_ID"
QUESTION_ID = "QUESTION_ID"
ANSWER_TEXT = "ANSWER_TEXT"
ASSIGNED_TO_USER_ID = "ASSIGNED_TO_USER_ID"
UPDATED_AT = "UPDATED_AT"
CREATED_AT = "CREATED_AT"
CONFIDENCE_SCORE = "CONFIDENCE_SCORE"

# Claims queue fields
PATIENT_NAME = "PATIENT_NAME"
DEFENDANT_NAME = "DEFENDANT_NAME"
FILE_NUMBER = "FILE_NUMBER"
PRIORITY = "PRIORITY"
DATE_REQUESTED = "DATE_REQUESTED"

# Notification fields
NOTIFICATION_ID = "NOTIFICATION_ID"
EVENT_TITLE = "EVENT_TITLE"
EVENT_MESSAGE = "EVENT_MESSAGE"
EVENT_PRIORITY = "EVENT_PRIORITY"
EVENT_TS = "EVENT_TS"
IS_READ = "IS_READ"
