"""Centralized column-name constants for Snowflake objects used in UI/services."""

# Shared fields
CLAIM_ID = "CLAIM_ID"
STATUS = "STATUS"
LAST_UPDATED_TS = "LAST_UPDATED_TS"
USERNAME = "USERNAME"
ASSIGNED_TO = "ASSIGNED_TO"

# Claims queue fields
PATIENT_NAME = "PATIENT_NAME"
DEFENDANT_NAME = "DEFENDANT_NAME"
FILE_NUMBER = "FILE_NUMBER"
PRIORITY = "PRIORITY"
DATE_REQUESTED = "DATE_REQUESTED"

# Notification fields
NOTIFICATION_ID = "NOTIFICATION_ID"
EVENT_TITLE = "EVENT_TITLE"
EVENT_MESSAGE = "EVENT_MESSAGE"
EVENT_PRIORITY = "EVENT_PRIORITY"
EVENT_TS = "EVENT_TS"
IS_READ = "IS_READ"
