"""Central Snowflake object name registry."""

SNOWFLAKE_DATABASE = "MFQ_DEV_DWH"
SNOWFLAKE_SCHEMA = "APP"

MFQ_CLAIMS_FQN = f"{SNOWFLAKE_DATABASE}.{SNOWFLAKE_SCHEMA}.MFQ_CLAIMS"
MFQ_CLAIM_DEFENDANTS_FQN = f"{SNOWFLAKE_DATABASE}.{SNOWFLAKE_SCHEMA}.MFQ_CLAIM_DEFENDANTS"

# Claims domain
MFQ_RECENT_CLAIMS_VIEW = MFQ_CLAIMS_FQN
MFQ_CLAIM_DETAIL_VIEW = MFQ_CLAIMS_FQN
MFQ_FORM_WORKSPACE_VIEW = "MFQ_FORM_WORKSPACE_VW"
MFQ_CLAIM_DEFENDANTS_TABLE = MFQ_CLAIM_DEFENDANTS_FQN
MFQ_RECORD_SUMMARY_TABLE = "MFQ_RECORD_SUMMARY"
MFQ_MEDCRON_SUMMARY_TABLE = "MFQ_MEDCRON_SUMMARY"
MFQ_LEGAL_MEMO_TABLE = "MFQ_LEGAL_MEMO"
MFQ_DOCUMENTS_TABLE = "MFQ_DOCUMENTS"
MFQ_ASSIGNMENT_QUEUE_VIEW = "MFQ_ASSIGNMENT_QUEUE_VW"
MFQ_STATUS_HISTORY_TABLE = "MFQ_STATUS_HISTORY"
MFQ_CLAIMS_TABLE = MFQ_CLAIMS_FQN
MFQ_ASSIGNMENTS_TABLE = "MFQ_ASSIGNMENTS"
MFQ_ASSIGNMENT_SECTIONS_TABLE = "MFQ_ASSIGNMENT_SECTIONS"

# MFQ data
MFQ_SECTIONS_TABLE = "MFQ_SECTIONS"
MFQ_QUESTIONS_TABLE = "MFQ_QUESTIONS"
MFQ_ANSWERS_TABLE = "MFQ_ANSWERS"
MFQ_QUESTION_CONFIDENCE_TABLE = "MFQ_QUESTION_CONFIDENCE"
MFQ_SECTION_CONFIDENCE_TABLE = "MFQ_SECTION_CONFIDENCE"
LLM_EVALUATION_TABLE = "LLM_EVALUATION"

# Notifications
MFQ_NOTIFICATIONS_VIEW = "MFQ_NOTIFICATIONS_VW"
MFQ_NOTIFICATIONS_TABLE = "MFQ_NOTIFICATIONS"

# Users / RBAC
MFQ_USERS_TABLE = "MFQ_USERS"
MFQ_USER_ROLES_TABLE = "MFQ_USER_ROLES"
MFQ_ROLES_TABLE = "MFQ_ROLES"
APP_USER_TABLE = "APP_USER"
APP_USER_ROLE_TABLE = "APP_USER_ROLE"
APP_ROLE_TABLE = "APP_ROLE"
APP_PERMISSION_TABLE = "APP_PERMISSION"
APP_ROLE_PERMISSION_TABLE = "APP_ROLE_PERMISSION"
