CLAIM_STATUSES = ["MFQ Generated", "Assigned", "Approved", "Rejected"]
CLAIM_PRIORITIES = ["Critical", "High", "Medium", "Low"]

ROLE_CLAIMS_ANALYST = "CLAIMS_ANALYST"
ROLE_ADVICE_TEAM = "ADVICE_TEAM"
ROLE_MEDICAL_FACULTY = "MEDICAL_FACULTY"
ROLE_EXECUTIVE = "EXECUTIVE"
ROLE_ADMIN = "ADMIN"

EDIT_ALL_ROLES = {
    ROLE_CLAIMS_ANALYST,
    ROLE_ADMIN,
}