USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

DELETE FROM NOTIFICATION_READ_STATUS WHERE READ_STATUS_ID LIKE 'RDS-%';
DELETE FROM NOTIFICATION_EVENT WHERE NOTIFICATION_ID LIKE 'NTF-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM CLAIM_DOCUMENT WHERE CLAIM_DOCUMENT_ID LIKE 'DOC-%' OR CLAIM_ID LIKE 'CLM-%' OR DEFENDANT_ID LIKE 'DEF-%';
DELETE FROM MISSING_DOCUMENT_REQUEST WHERE REQUEST_ID LIKE 'MDR-%' OR CLAIM_ID LIKE 'CLM-%' OR DEFENDANT_ID LIKE 'DEF-%';
DELETE FROM APP_WORKFLOW_EVENT WHERE WORKFLOW_EVENT_ID LIKE 'WFE-%' OR CLAIM_ID LIKE 'CLM-%' OR DEFENDANT_ID LIKE 'DEF-%';
DELETE FROM APPIAN_OUTBOX_EVENT WHERE OUTBOX_EVENT_ID LIKE 'AOB-%' OR ENTITY_ID LIKE 'CLM-%' OR ENTITY_ID LIKE 'DEF-%';
DELETE FROM APP_AUDIT_LOG WHERE AUDIT_ID LIKE 'AUD-%' OR ENTITY_ID LIKE 'CLM-%' OR ENTITY_ID LIKE 'DEF-%';
DELETE FROM CLAIM_SECTION_ASSIGNMENT WHERE SECTION_ASSIGNMENT_ID LIKE 'CSA-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM CLAIM_ASSIGNMENT WHERE ASSIGNMENT_ID LIKE 'ASG-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM HUMAN_REVIEW WHERE REVIEW_ID LIKE 'REV-%' OR CLAIM_ID LIKE 'CLM-%' OR DEFENDANT_ID LIKE 'DEF-%';
DELETE FROM CLAIM_SUMMARY WHERE SUMMARY_ID LIKE 'SUM-%' OR CLAIM_ID LIKE 'CLM-%' OR DEFENDANT_ID LIKE 'DEF-%';
DELETE FROM PIPELINE_RUN WHERE RUN_ID LIKE 'RUN-%' OR CLAIM_ID LIKE 'CLM-%' OR DEFENDANT_ID LIKE 'DEF-%';
DELETE FROM MFQ_ANSWER WHERE ANSWER_ID LIKE 'ANS-%' OR DEFENDANT_ID LIKE 'DEF-%';
DELETE FROM CLAIM_DEFENDANT WHERE DEFENDANT_ID LIKE 'DEF-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM CLAIM WHERE CLAIM_ID LIKE 'CLM-%';

DELETE FROM FACULTY_SPECIALTY WHERE FACULTY_SPECIALTY_ID LIKE 'FSP-%' OR FACULTY_ID LIKE 'FAC-%';
DELETE FROM FACULTY_PROFILE WHERE FACULTY_ID LIKE 'FAC-%' OR USER_ID LIKE 'USR-%';
DELETE FROM APP_USER_ROLE WHERE USER_ROLE_ID LIKE 'URO-%' OR USER_ID LIKE 'USR-%' OR ROLE_ID LIKE 'ROLE-%';
DELETE FROM APP_ROLE_PERMISSION WHERE ROLE_PERMISSION_ID LIKE 'ROP-%' OR ROLE_ID LIKE 'ROLE-%' OR PERMISSION_ID LIKE 'PERM-%';
DELETE FROM APP_PERMISSION WHERE PERMISSION_ID LIKE 'PERM-%';
DELETE FROM APP_ROLE WHERE ROLE_ID LIKE 'ROLE-%';
DELETE FROM APP_USER WHERE USER_ID LIKE 'USR-%';
