USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

DELETE FROM MFQ_ASSIGNMENT_SECTIONS WHERE ASSIGNMENT_SECTION_ID LIKE 'ASSEC-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM MFQ_ASSIGNMENTS WHERE ASSIGNMENT_ID LIKE 'ASG-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM MFQ_NOTIFICATIONS WHERE NOTIFICATION_ID LIKE 'NTF-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM MFQ_REPORTS WHERE REPORT_ID LIKE 'RPT-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM MFQ_DOCUMENTS WHERE DOCUMENT_ID LIKE 'DOC-%' OR CLAIM_ID LIKE 'CLM-%' OR DEFENDANT_ID LIKE 'DEF-%';
DELETE FROM MFQ_RECORD_SUMMARY WHERE RECORD_SUMMARY_ID LIKE 'RS-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM MFQ_MEDCRON_SUMMARY WHERE MEDCRON_SUMMARY_ID LIKE 'MS-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM MFQ_LEGAL_MEMO WHERE LEGAL_MEMO_ID LIKE 'LM-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM MFQ_QUESTION_CONFIDENCE WHERE QUESTION_CONFIDENCE_ID LIKE 'QC-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM MFQ_SECTION_CONFIDENCE WHERE SECTION_CONFIDENCE_ID LIKE 'SC-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM MFQ_AI_CONFIDENCE WHERE CONFIDENCE_ID LIKE 'AIC-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM MFQ_ANSWERS WHERE ANSWER_ID LIKE 'ANS-%' OR CLAIM_ID LIKE 'CLM-%' OR DEFENDANT_ID LIKE 'DEF-%';
DELETE FROM MFQ_PIPELINE_RUNS WHERE RUN_ID LIKE 'RUN-%' OR CLAIM_ID LIKE 'CLM-%' OR DEFENDANT_ID LIKE 'DEF-%';
DELETE FROM MFQ_CLAIM_DEFENDANTS WHERE DEFENDANT_ID LIKE 'DEF-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM MFQ_STATUS_HISTORY WHERE STATUS_HISTORY_ID LIKE 'HIS-%' OR CLAIM_ID LIKE 'CLM-%';
DELETE FROM MFQ_AUDIT_LOG WHERE AUDIT_ID LIKE 'AUD-%' OR ENTITY_ID LIKE 'CLM-%';
DELETE FROM MFQ_CLAIMS WHERE CLAIM_ID LIKE 'CLM-%';

DELETE FROM MFQ_USER_ROLES WHERE USER_ROLE_ID LIKE 'URO-%' OR USER_ID LIKE 'USR-%' OR ROLE_ID LIKE 'ROLE-%';
DELETE FROM MFQ_RBAC_ACCESS WHERE ACCESS_ID LIKE 'RBA-%' OR ROLE_ID LIKE 'ROLE-%';
DELETE FROM MFQ_ROLES WHERE ROLE_ID LIKE 'ROLE-%';
DELETE FROM MFQ_USERS WHERE USER_ID LIKE 'USR-%';
