USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE MFQ_SECTIONS (
  SECTION_ID STRING NOT NULL,
  FORM_KEY STRING NOT NULL,
  SECTION_KEY STRING NOT NULL,
  SECTION_NAME STRING NOT NULL,
  DISPLAY_ORDER NUMBER NOT NULL,
  IS_SKIPPABLE BOOLEAN DEFAULT FALSE,
  SKIP_CONDITION VARIANT,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (SECTION_ID)
);

CREATE OR REPLACE TABLE MFQ_QUESTIONS (
  QUESTION_ID STRING NOT NULL,
  FORM_KEY STRING NOT NULL,
  SECTION_ID STRING NOT NULL,
  QUESTION_KEY STRING NOT NULL,
  PARENT_QUESTION_ID STRING,
  DISPLAY_ORDER NUMBER NOT NULL,
  QUESTION_VERSION NUMBER DEFAULT 1,
  IS_CURRENT BOOLEAN DEFAULT TRUE,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  STATUS STRING DEFAULT 'ACTIVE',
  PROMPT_TEMPLATE_KEY STRING,
  QUESTION_TEXT STRING NOT NULL,
  ANSWER_TYPE STRING NOT NULL,
  ALLOWED_VALUES VARIANT,
  VISIBILITY_RULE VARIANT,
  SEARCH_TOP_K NUMBER,
  SEARCH_DOC_TYPE_FILTER VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (QUESTION_ID)
);

CREATE OR REPLACE TABLE MFQ_ANSWERS (
  ANSWER_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING NOT NULL,
  QUESTION_ID STRING NOT NULL,
  ANSWER_TEXT STRING,
  ANSWER_JSON VARIANT,
  CONFIDENCE_SCORE FLOAT,
  STATUS STRING DEFAULT 'GENERATED',
  IS_CURRENT BOOLEAN DEFAULT TRUE,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ANSWER_ID)
);
