USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE MFQ_CLAIMS (
  CLAIM_ID STRING NOT NULL,
  FILE_NUMBER STRING NOT NULL,
  PATIENT_NAME STRING,
  STATUS STRING DEFAULT 'MFQ Generated',
  PRIORITY STRING DEFAULT 'Medium',
  DATE_REQUESTED DATE,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (CLAIM_ID)
);

CREATE OR REPLACE TABLE MFQ_CLAIM_DEFENDANTS (
  DEFENDANT_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_NAME STRING NOT NULL,
  SPECIALTY STRING,
  BRIEF_SYNOPSIS STRING,
  ALLEGED_INJURY_TERMS STRING,
  ALLEGATION_SUMMARY STRING,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (DEFENDANT_ID)
);

CREATE OR REPLACE TABLE MFQ_PIPELINE_RUNS (
  RUN_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING NOT NULL,
  STATUS STRING NOT NULL,
  AI_CONFIDENCE FLOAT,
  STARTED_TS TIMESTAMP_LTZ,
  COMPLETED_TS TIMESTAMP_LTZ,
  PRIMARY KEY (RUN_ID)
);

CREATE OR REPLACE TABLE MFQ_SECTIONS (
  SECTION_ID STRING NOT NULL,
  FORM_KEY STRING NOT NULL,
  SECTION_KEY STRING NOT NULL,
  SECTION_NAME STRING NOT NULL,
  DISPLAY_ORDER NUMBER NOT NULL,
  IS_SKIPPABLE BOOLEAN DEFAULT FALSE,
  SKIP_CONDITION VARIANT,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (SECTION_ID)
);

CREATE OR REPLACE TABLE MFQ_QUESTIONS (
  QUESTION_ID STRING NOT NULL,
  FORM_KEY STRING NOT NULL,
  SECTION_ID STRING NOT NULL,
  QUESTION_KEY STRING NOT NULL,
  PARENT_QUESTION_ID STRING,
  DISPLAY_ORDER NUMBER NOT NULL,
  QUESTION_VERSION NUMBER DEFAULT 1,
  IS_CURRENT BOOLEAN DEFAULT TRUE,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  STATUS STRING DEFAULT 'ACTIVE',
  PROMPT_TEMPLATE_KEY STRING,
  QUESTION_TEXT STRING NOT NULL,
  ANSWER_TYPE STRING NOT NULL,
  ALLOWED_VALUES VARIANT,
  VISIBILITY_RULE VARIANT,
  SEARCH_TOP_K NUMBER,
  SEARCH_DOC_TYPE_FILTER VARIANT,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (QUESTION_ID)
);

CREATE OR REPLACE TABLE MFQ_ANSWERS (
  ANSWER_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING NOT NULL,
  QUESTION_ID STRING NOT NULL,
  ANSWER_TEXT STRING,
  ANSWER_JSON VARIANT,
  CONFIDENCE_SCORE FLOAT,
  STATUS STRING DEFAULT 'GENERATED',
  IS_CURRENT BOOLEAN DEFAULT TRUE,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ANSWER_ID)
);

CREATE OR REPLACE TABLE MFQ_AI_CONFIDENCE (
  CONFIDENCE_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING,
  OVERALL_CONFIDENCE_SCORE FLOAT,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (CONFIDENCE_ID)
);

CREATE OR REPLACE TABLE MFQ_SECTION_CONFIDENCE (
  SECTION_CONFIDENCE_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING,
  SECTION_ID STRING NOT NULL,
  CONFIDENCE_SCORE FLOAT,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (SECTION_CONFIDENCE_ID)
);

CREATE OR REPLACE TABLE MFQ_QUESTION_CONFIDENCE (
  QUESTION_CONFIDENCE_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING,
  QUESTION_ID STRING NOT NULL,
  CONFIDENCE_SCORE FLOAT,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (QUESTION_CONFIDENCE_ID)
);

CREATE OR REPLACE TABLE MFQ_ASSIGNMENTS (
  ASSIGNMENT_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  ASSIGNED_TO_USER_ID STRING NOT NULL,
  ASSIGNED_BY_USER_ID STRING,
  ASSIGNMENT_STATUS STRING,
  PRIORITY STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ASSIGNMENT_ID)
);

CREATE OR REPLACE TABLE MFQ_ASSIGNMENT_SECTIONS (
  ASSIGNMENT_SECTION_ID STRING NOT NULL,
  ASSIGNMENT_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  SECTION_ID STRING NOT NULL,
  ASSIGNED_TO_USER_ID STRING NOT NULL,
  ASSIGNMENT_STATUS STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ASSIGNMENT_SECTION_ID)
);

CREATE OR REPLACE TABLE MFQ_NOTIFICATIONS (
  NOTIFICATION_ID STRING NOT NULL,
  USER_ID STRING NOT NULL,
  EVENT_TYPE STRING,
  EVENT_TITLE STRING,
  EVENT_MESSAGE STRING,
  CLAIM_ID STRING,
  EVENT_PRIORITY STRING,
  EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  IS_READ BOOLEAN DEFAULT FALSE,
  PAYLOAD VARIANT,
  PRIMARY KEY (NOTIFICATION_ID)
);

CREATE OR REPLACE TABLE MFQ_RECORD_SUMMARY (
  RECORD_SUMMARY_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING,
  SUMMARY_TEXT STRING,
  GENERATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (RECORD_SUMMARY_ID)
);

CREATE OR REPLACE TABLE MFQ_MEDCRON_SUMMARY (
  MEDCRON_SUMMARY_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING,
  SUMMARY_TEXT STRING,
  GENERATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (MEDCRON_SUMMARY_ID)
);

CREATE OR REPLACE TABLE MFQ_LEGAL_MEMO (
  LEGAL_MEMO_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING,
  SUMMARY_TEXT STRING,
  GENERATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (LEGAL_MEMO_ID)
);

CREATE OR REPLACE TABLE MFQ_DOCUMENTS (
  DOCUMENT_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING,
  FILE_NAME STRING,
  DOC_TYPE STRING,
  OCR_STATUS STRING,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (DOCUMENT_ID)
);

CREATE OR REPLACE TABLE MFQ_REPORTS (
  REPORT_ID STRING NOT NULL,
  CLAIM_ID STRING,
  REPORT_TYPE STRING,
  REPORT_STATUS STRING,
  REPORT_PAYLOAD VARIANT,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (REPORT_ID)
);

CREATE OR REPLACE TABLE MFQ_USERS (
  USER_ID STRING NOT NULL,
  USERNAME STRING NOT NULL,
  EMAIL STRING,
  DISPLAY_NAME STRING,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (USER_ID)
);

CREATE OR REPLACE TABLE MFQ_ROLES (
  ROLE_ID STRING NOT NULL,
  ROLE_CODE STRING NOT NULL,
  ROLE_NAME STRING NOT NULL,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (ROLE_ID)
);

CREATE OR REPLACE TABLE MFQ_USER_ROLES (
  USER_ROLE_ID STRING NOT NULL,
  USER_ID STRING NOT NULL,
  ROLE_ID STRING NOT NULL,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (USER_ROLE_ID)
);

CREATE OR REPLACE TABLE MFQ_RBAC_ACCESS (
  ACCESS_ID STRING NOT NULL,
  ROLE_ID STRING NOT NULL,
  PERMISSION_CODE STRING NOT NULL,
  PERMISSION_NAME STRING NOT NULL,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (ACCESS_ID)
);

CREATE OR REPLACE TABLE MFQ_AUDIT_LOG (
  AUDIT_ID STRING NOT NULL,
  ENTITY_TYPE STRING,
  ENTITY_ID STRING,
  ACTION_TYPE STRING,
  ACTION_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ACTOR_USER_ID STRING,
  PRIMARY KEY (AUDIT_ID)
);

CREATE OR REPLACE TABLE MFQ_STATUS_HISTORY (
  STATUS_HISTORY_ID STRING NOT NULL,
  CLAIM_ID STRING,
  DEFENDANT_ID STRING,
  EVENT_TYPE STRING,
  FROM_STATUS STRING,
  TO_STATUS STRING,
  EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  EVENT_BY_USER_ID STRING,
  EVENT_NOTE STRING,
  PRIMARY KEY (STATUS_HISTORY_ID)
);

-- pipeline config retained
CREATE OR REPLACE TABLE PIPELINE_CONFIG (CONFIG_KEY STRING, CONFIG_VALUE STRING, DATA_TYPE STRING, DESCRIPTION STRING, PRIMARY KEY (CONFIG_KEY));
CREATE OR REPLACE TABLE LLM_CONFIG (MODEL_KEY STRING, PROVIDER STRING, ENDPOINT_URL STRING, SECRET_NAME STRING, TEMPERATURE FLOAT, MAX_TOKENS NUMBER, ADDITIONAL_PARAMETERS VARIANT, IS_ACTIVE BOOLEAN, PRIMARY KEY (MODEL_KEY));
CREATE OR REPLACE TABLE LLM_ROUTING (ROUTE_KEY STRING, TASK_TYPE STRING, SECTION_KEY STRING, QUESTION_KEY STRING, GENERATION_MODEL_KEY STRING, EVALUATION_MODEL_KEY STRING, EMBEDDING_MODEL_KEY STRING, PRIORITY NUMBER, IS_ACTIVE BOOLEAN, PRIMARY KEY (ROUTE_KEY));
CREATE OR REPLACE TABLE WORKFLOW_STATUS_DEF (ENTITY_TYPE STRING, STATUS_CODE STRING, ALLOWED_NEXT VARIANT, DESCRIPTION STRING, PRIMARY KEY (ENTITY_TYPE, STATUS_CODE));
CREATE OR REPLACE TABLE SUMMARY_CONFIG (SUMMARY_TYPE STRING, DISPLAY_ORDER NUMBER, SECTION_KEYS VARIANT, SEARCH_QUERY STRING, WORD_TARGET NUMBER, INSTRUCTIONS STRING, IS_ACTIVE BOOLEAN, PRIMARY KEY (SUMMARY_TYPE));
