USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS LLM_EVALUATION (
  EVALUATION_ID STRING,
  ENTITY_ID STRING,
  FAITHFULNESS_SCORE FLOAT,
  HALLUCINATION_FLAG BOOLEAN,
  NEEDS_HUMAN_REVIEW BOOLEAN,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW VW_CURRENT_ANSWERS AS
SELECT *
FROM MFQ_ANSWERS
WHERE IS_CURRENT = TRUE;
