USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

CREATE TABLE IF NOT EXISTS LLM_EVALUATION (
  EVALUATION_ID STRING,
  ENTITY_ID STRING,
  FAITHFULNESS_SCORE FLOAT,
  HALLUCINATION_FLAG BOOLEAN,
  NEEDS_HUMAN_REVIEW BOOLEAN,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE VIEW VW_CURRENT_ANSWERS AS
SELECT *
FROM MFQ_ANSWERS
WHERE IS_CURRENT = TRUE;

CREATE OR REPLACE VIEW VW_MFQ_CLAIMS AS
WITH DEFENDANT_SUMMARY AS (
    SELECT
        CLAIM_ID,

        LISTAGG(DISTINCT DEFENDANT_NAME, ', ')
            WITHIN GROUP (ORDER BY DEFENDANT_NAME) AS DEFENDANT_NAME,

        MAX(
            CASE
                WHEN CONFIDENCE_SCORE IS NULL THEN NULL
                WHEN CONFIDENCE_SCORE <= 1 THEN CONFIDENCE_SCORE * 100
                ELSE CONFIDENCE_SCORE
            END
        ) AS AI_CONFIDENCE

    FROM MFQ_CLAIM_DEFENDANTS
    WHERE IS_CURRENT = TRUE
    GROUP BY CLAIM_ID
)
SELECT
    c.CLAIM_ID AS CLAIM_ID,

    CONCAT(
        COALESCE(c.PATIENT_NAME, ''),
        ' / ',
        COALESCE(d.DEFENDANT_NAME, '')
    ) AS PATIENT_DEFENDANT,

    COALESCE(c.MINIMUM_GATE_STATUS, c.DEFENDANT_STATUS) AS MFQ_STATUS,

    c.SYNC_STATUS AS WORKFLOW_STATUS,

    NULL AS PRIORITY,

    c.CLAIM_STATUS AS CLAIM_STATUS,

    NULL AS CLAIM_TYPE,

    c.CREATED_AT AS DATE_REQUESTED,

    ROUND(d.AI_CONFIDENCE, 0) AS AI_CONFIDENCE

FROM MFQ_CLAIMS c
LEFT JOIN DEFENDANT_SUMMARY d
    ON TRIM(TO_VARCHAR(c.CLAIM_ID)) = TRIM(TO_VARCHAR(d.CLAIM_ID));

CREATE OR REPLACE VIEW MFQ_DASHBOARD_SUMMARY_VW AS
SELECT
    COUNT(*) AS TOTAL_ACTIVE_CLAIMS,
    COALESCE(COUNT_IF(UPPER(TRIM(MFQ_STATUS)) = 'MFQ GENERATED'), 0) AS MFQ_GENERATED_COUNT,
    COALESCE(COUNT_IF(UPPER(TRIM(MFQ_STATUS)) = 'ASSIGNED'), 0) AS ASSIGNED_COUNT,
    COALESCE(COUNT_IF(UPPER(TRIM(MFQ_STATUS)) = 'ON HOLD'), 0) AS ON_HOLD_COUNT,
    COALESCE(COUNT_IF(UPPER(TRIM(MFQ_STATUS)) = 'APPROVED'), 0) AS APPROVED_COUNT,
    COALESCE(COUNT_IF(UPPER(TRIM(MFQ_STATUS)) = 'REJECTED'), 0) AS REJECTED_COUNT
FROM VW_MFQ_CLAIMS;

CREATE OR REPLACE VIEW MFQ_CLAIM_DETAIL_VW AS
WITH DEFENDANT_SUMMARY AS (
    SELECT
        CLAIM_ID,

        LISTAGG(DISTINCT DEFENDANT_NAME, ', ')
            WITHIN GROUP (ORDER BY DEFENDANT_NAME) AS DEFENDANT_NAME,

        LISTAGG(DISTINCT DEFENDANT_TYPE, ', ')
            WITHIN GROUP (ORDER BY DEFENDANT_TYPE) AS DEFENDANT_TYPE,

        LISTAGG(DISTINCT SOURCE_FILE_NAME, ', ')
            WITHIN GROUP (ORDER BY SOURCE_FILE_NAME) AS SOURCE_FILE_NAME,

        MAX(
            CASE
                WHEN CONFIDENCE_SCORE IS NULL THEN NULL
                WHEN CONFIDENCE_SCORE <= 1 THEN CONFIDENCE_SCORE * 100
                ELSE CONFIDENCE_SCORE
            END
        ) AS AI_CONFIDENCE,

        COUNT(*) AS DEFENDANT_COUNT,

        ARRAY_AGG(
            OBJECT_CONSTRUCT(
                'DEFENDANT_ID', DEFENDANT_ID,
                'DEFENDANT_NAME', DEFENDANT_NAME,
                'DEFENDANT_TYPE', DEFENDANT_TYPE,
                'SOURCE_DOCUMENT_ID', SOURCE_DOCUMENT_ID,
                'SOURCE_FILE_NAME', SOURCE_FILE_NAME,
                'EVIDENCE_TEXT', EVIDENCE_TEXT,
                'EXTRACTION_METHOD', EXTRACTION_METHOD,
                'CONFIDENCE_SCORE', CONFIDENCE_SCORE,
                'EXTRACTION_STATUS', EXTRACTION_STATUS,
                'IS_CURRENT', IS_CURRENT,
                'EXTRACTION_RUN_ID', EXTRACTION_RUN_ID,
                'PAYLOAD', PAYLOAD,
                'CREATED_AT', CREATED_AT,
                'UPDATED_AT', UPDATED_AT
            )
        ) AS DEFENDANTS_JSON

    FROM MFQ_CLAIM_DEFENDANTS
    WHERE IS_CURRENT = TRUE
    GROUP BY CLAIM_ID
)
SELECT
    c.CLAIM_ID,

    c.DRAWER_NAME,
    c.FOLDER_NAME,

    c.PATIENT_NAME,

    CONCAT(
        COALESCE(c.PATIENT_NAME, ''),
        ' / ',
        COALESCE(d.DEFENDANT_NAME, '')
    ) AS PATIENT_DEFENDANT,

    d.DEFENDANT_NAME,
    d.DEFENDANT_TYPE,
    d.DEFENDANT_COUNT,
    d.SOURCE_FILE_NAME,
    ROUND(d.AI_CONFIDENCE, 0) AS AI_CONFIDENCE,
    d.DEFENDANTS_JSON,

    c.FIRST_DOCUMENT_DATE,
    c.LAST_DOCUMENT_DATE,
    c.SOURCE_DOCUMENT_COUNT,

    c.CLAIM_STATUS,

    c.SYNC_STATUS AS WORKFLOW_STATUS,

    c.DEFENDANT_STATUS,

    COALESCE(c.MINIMUM_GATE_STATUS, c.DEFENDANT_STATUS) AS MFQ_STATUS,

    c.MINIMUM_GATE_STATUS,
    c.MINIMUM_GATE_DETAILS,

    c.EMBEDDING_STATUS,
    c.LAST_SYNCED_AT,

    c.CREATED_AT AS DATE_REQUESTED,
    c.CREATED_AT,
    c.UPDATED_AT

FROM MFQ_CLAIMS c
LEFT JOIN DEFENDANT_SUMMARY d
    ON TRIM(TO_VARCHAR(c.CLAIM_ID)) = TRIM(TO_VARCHAR(d.CLAIM_ID));
