USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

-- compatibility views for legacy object references
CREATE OR REPLACE VIEW CLAIM AS SELECT * FROM MFQ_CLAIMS;
CREATE OR REPLACE VIEW CLAIM_DEFENDANT AS
SELECT
  DEFENDANT_ID,
  CLAIM_ID,
  DEFENDANT_NAME,
  SPECIALTY,
  BRIEF_SYNOPSIS,
  ALLEGED_INJURY_TERMS,
  ALLEGATION_SUMMARY,
  CREATED_TS,
  LAST_UPDATED_TS
FROM MFQ_CLAIM_DEFENDANTS;
CREATE OR REPLACE VIEW PIPELINE_RUN AS SELECT * FROM MFQ_PIPELINE_RUNS;
CREATE OR REPLACE VIEW APP_USER AS SELECT * FROM MFQ_USERS;
CREATE OR REPLACE VIEW APP_ROLE AS SELECT * FROM MFQ_ROLES;
CREATE OR REPLACE VIEW APP_USER_ROLE AS SELECT * FROM MFQ_USER_ROLES;
CREATE OR REPLACE VIEW APP_PERMISSION AS
SELECT
  ACCESS_ID AS PERMISSION_ID,
  PERMISSION_CODE,
  PERMISSION_NAME
FROM MFQ_RBAC_ACCESS;
CREATE OR REPLACE VIEW APP_ROLE_PERMISSION AS
SELECT
  ACCESS_ID AS ROLE_PERMISSION_ID,
  ROLE_ID,
  ACCESS_ID AS PERMISSION_ID,
  IS_ACTIVE
FROM MFQ_RBAC_ACCESS;
CREATE OR REPLACE VIEW CLAIM_ASSIGNMENT AS SELECT * FROM MFQ_ASSIGNMENTS;
CREATE OR REPLACE VIEW CLAIM_SECTION_ASSIGNMENT AS
SELECT
  ASSIGNMENT_SECTION_ID AS SECTION_ASSIGNMENT_ID,
  CLAIM_ID,
  SECTION_ID,
  ASSIGNED_TO_USER_ID,
  ASSIGNMENT_STATUS,
  ASSIGNED_AT
FROM MFQ_ASSIGNMENT_SECTIONS;
CREATE OR REPLACE VIEW NOTIFICATION_EVENT AS SELECT * FROM MFQ_NOTIFICATIONS;
CREATE OR REPLACE VIEW CLAIM_DOCUMENT AS
SELECT
  DOCUMENT_ID AS CLAIM_DOCUMENT_ID,
  CLAIM_ID,
  DEFENDANT_ID,
  FILE_NAME,
  DOC_TYPE,
  OCR_STATUS,
  CREATED_TS
FROM MFQ_DOCUMENTS;

CREATE OR REPLACE VIEW MFQ_SECTIONS_VW AS
SELECT
  FORM_KEY,
  SECTION_ID,
  SECTION_KEY,
  SECTION_NAME,
  DISPLAY_ORDER,
  DISPLAY_ORDER AS SECTION_ORDER,
  IS_SKIPPABLE,
  SKIP_CONDITION,
  IS_ACTIVE
FROM MFQ_SECTIONS
WHERE IS_ACTIVE = TRUE;

CREATE OR REPLACE VIEW MFQ_QUESTIONS_VW AS
SELECT
  FORM_KEY,
  SECTION_ID,
  QUESTION_ID,
  QUESTION_KEY,
  PARENT_QUESTION_ID,
  QUESTION_TEXT,
  DISPLAY_ORDER,
  DISPLAY_ORDER AS QUESTION_ORDER,
  ANSWER_TYPE,
  ALLOWED_VALUES,
  VISIBILITY_RULE,
  SEARCH_TOP_K,
  SEARCH_DOC_TYPE_FILTER,
  IS_CURRENT,
  IS_ACTIVE
FROM MFQ_QUESTIONS
WHERE IS_CURRENT = TRUE
  AND IS_ACTIVE = TRUE;

CREATE OR REPLACE VIEW MFQ_CLAIMS_VW AS
SELECT
  c.CLAIM_ID,
  c.FILE_NUMBER,
  c.PATIENT_NAME,
  c.STATUS,
  COALESCE(c.PRIORITY, ca.PRIORITY, 'Medium') AS PRIORITY,
  c.DATE_REQUESTED,
  d.DEFENDANT_ID,
  d.DEFENDANT_NAME,
  d.SPECIALTY,
  u.USERNAME AS ASSIGNED_TO,
  COALESCE(aic.OVERALL_CONFIDENCE_SCORE, pr.AI_CONFIDENCE) AS AI_CONFIDENCE,
  c.LAST_UPDATED_TS
FROM MFQ_CLAIMS c
JOIN MFQ_CLAIM_DEFENDANTS d ON c.CLAIM_ID = d.CLAIM_ID
LEFT JOIN MFQ_ASSIGNMENTS ca ON c.CLAIM_ID = ca.CLAIM_ID
LEFT JOIN MFQ_USERS u ON ca.ASSIGNED_TO_USER_ID = u.USER_ID
LEFT JOIN MFQ_PIPELINE_RUNS pr ON pr.CLAIM_ID = c.CLAIM_ID AND pr.DEFENDANT_ID = d.DEFENDANT_ID
LEFT JOIN MFQ_AI_CONFIDENCE aic ON aic.CLAIM_ID = c.CLAIM_ID AND COALESCE(aic.DEFENDANT_ID, d.DEFENDANT_ID) = d.DEFENDANT_ID;

CREATE OR REPLACE VIEW MFQ_RECENT_CLAIMS_VW AS
SELECT *
FROM MFQ_CLAIMS_VW
QUALIFY ROW_NUMBER() OVER (ORDER BY LAST_UPDATED_TS DESC, CLAIM_ID) <= 100;

CREATE OR REPLACE VIEW MFQ_DASHBOARD_SUMMARY_VW AS
SELECT
  COUNT(*) AS TOTAL_ACTIVE_CLAIMS,
  COALESCE(COUNT_IF(STATUS = 'MFQ Generated'), 0) AS MFQ_GENERATED_COUNT,
  COALESCE(COUNT_IF(STATUS = 'Assigned'), 0) AS ASSIGNED_COUNT,
  COALESCE(COUNT_IF(STATUS = 'On Hold'), 0) AS ON_HOLD_COUNT,
  COALESCE(COUNT_IF(STATUS = 'Approved'), 0) AS APPROVED_COUNT,
  COALESCE(COUNT_IF(STATUS = 'Rejected'), 0) AS REJECTED_COUNT
FROM MFQ_CLAIMS_VW;

CREATE OR REPLACE VIEW MFQ_DASHBOARD_KPI_VW AS
SELECT
  TOTAL_ACTIVE_CLAIMS,
  MFQ_GENERATED_COUNT,
  ASSIGNED_COUNT,
  ON_HOLD_COUNT,
  APPROVED_COUNT,
  REJECTED_COUNT
FROM MFQ_DASHBOARD_SUMMARY_VW;

CREATE OR REPLACE VIEW MFQ_CLAIM_DETAIL_VW AS
SELECT
  mc.*,
  rs.SUMMARY_TEXT AS RECORDS_SUMMARY,
  ms.SUMMARY_TEXT AS MEDCRON_TEXT,
  lm.SUMMARY_TEXT AS LEGAL_MEMO_TEXT
FROM MFQ_CLAIMS_VW mc
LEFT JOIN MFQ_RECORD_SUMMARY rs ON rs.CLAIM_ID = mc.CLAIM_ID
LEFT JOIN MFQ_MEDCRON_SUMMARY ms ON ms.CLAIM_ID = mc.CLAIM_ID
LEFT JOIN MFQ_LEGAL_MEMO lm ON lm.CLAIM_ID = mc.CLAIM_ID;

CREATE OR REPLACE VIEW MFQ_FORM_WORKSPACE_VW AS
SELECT
  mc.CLAIM_ID,
  mc.DEFENDANT_ID,
  s.SECTION_ID,
  s.SECTION_NAME,
  s.DISPLAY_ORDER AS SECTION_ORDER,
  q.QUESTION_ID,
  q.QUESTION_KEY,
  q.PARENT_QUESTION_ID,
  q.QUESTION_TEXT,
  q.DISPLAY_ORDER AS QUESTION_ORDER,
  q.ANSWER_TYPE,
  q.ALLOWED_VALUES,
  q.VISIBILITY_RULE,
  a.ANSWER_ID,
  a.ANSWER_TEXT,
  a.ANSWER_JSON,
  COALESCE(qc.CONFIDENCE_SCORE, a.CONFIDENCE_SCORE) AS CONFIDENCE_SCORE,
  a.STATUS AS ANSWER_STATUS
FROM MFQ_CLAIMS_VW mc
JOIN MFQ_SECTIONS s ON s.FORM_KEY = 'MFQ_V1' AND s.IS_ACTIVE = TRUE
JOIN MFQ_QUESTIONS q ON q.FORM_KEY = s.FORM_KEY AND q.SECTION_ID = s.SECTION_ID AND q.IS_CURRENT = TRUE AND q.IS_ACTIVE = TRUE
LEFT JOIN MFQ_ANSWERS a
  ON a.CLAIM_ID = mc.CLAIM_ID
 AND a.DEFENDANT_ID = mc.DEFENDANT_ID
 AND a.QUESTION_ID = q.QUESTION_ID
 AND a.IS_CURRENT = TRUE
LEFT JOIN MFQ_QUESTION_CONFIDENCE qc
  ON qc.CLAIM_ID = mc.CLAIM_ID
 AND COALESCE(qc.DEFENDANT_ID, mc.DEFENDANT_ID) = mc.DEFENDANT_ID
 AND qc.QUESTION_ID = q.QUESTION_ID;

CREATE OR REPLACE VIEW MFQ_NOTIFICATION_VW AS
SELECT
  n.NOTIFICATION_ID,
  n.USER_ID,
  u.USERNAME,
  n.EVENT_TYPE,
  n.EVENT_TITLE,
  n.EVENT_MESSAGE,
  n.CLAIM_ID,
  n.EVENT_PRIORITY,
  n.EVENT_TS,
  n.IS_READ
FROM MFQ_NOTIFICATIONS n
LEFT JOIN MFQ_USERS u ON u.USER_ID = n.USER_ID;

CREATE OR REPLACE VIEW MFQ_NOTIFICATIONS_VW AS
SELECT * FROM MFQ_NOTIFICATION_VW;

CREATE OR REPLACE VIEW MFQ_ASSIGNMENT_QUEUE_VW AS
SELECT
  ca.ASSIGNMENT_ID,
  ca.CLAIM_ID,
  c.PATIENT_NAME,
  d.DEFENDANT_NAME,
  d.SPECIALTY,
  ca.PRIORITY,
  ca.ASSIGNMENT_STATUS,
  ca.ASSIGNED_AT,
  au.USERNAME AS ASSIGNED_TO,
  assigner.USERNAME AS ASSIGNED_BY
FROM MFQ_ASSIGNMENTS ca
JOIN MFQ_CLAIMS c ON c.CLAIM_ID = ca.CLAIM_ID
JOIN MFQ_CLAIM_DEFENDANTS d ON d.CLAIM_ID = ca.CLAIM_ID
LEFT JOIN MFQ_USERS au ON au.USER_ID = ca.ASSIGNED_TO_USER_ID
LEFT JOIN MFQ_USERS assigner ON assigner.USER_ID = ca.ASSIGNED_BY_USER_ID;

CREATE OR REPLACE VIEW MFQ_REPORT_STATUS_VW AS
SELECT STATUS, COUNT(*) AS CLAIM_COUNT
FROM MFQ_CLAIMS_VW
GROUP BY STATUS;

CREATE OR REPLACE VIEW MFQ_REPORT_FACULTY_PERFORMANCE_VW AS
SELECT
  mc.ASSIGNED_TO AS FACULTY_USERNAME,
  COUNT(*) AS TOTAL_ASSIGNED,
  COUNT_IF(mc.STATUS = 'Approved') AS APPROVED_COUNT,
  AVG(COALESCE(mc.AI_CONFIDENCE, 0)) AS AVG_AI_CONFIDENCE
FROM MFQ_CLAIMS_VW mc
GROUP BY mc.ASSIGNED_TO;

CREATE OR REPLACE VIEW MFQ_REPORT_SPECIALTY_DISTRIBUTION_VW AS
SELECT SPECIALTY, COUNT(*) AS CLAIM_COUNT
FROM MFQ_CLAIMS_VW
GROUP BY SPECIALTY;
