USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

SET CLAIM_ID = 'CLM-1002';
SET DEFENDANT_ID = (
  SELECT DEFENDANT_ID
  FROM MFQ_CLAIM_DEFENDANTS
  WHERE CLAIM_ID = $CLAIM_ID
  ORDER BY DEFENDANT_ID
  LIMIT 1
);

UPDATE MFQ_ANSWERS
SET IS_CURRENT = FALSE,
    LAST_UPDATED_TS = CURRENT_TIMESTAMP()
WHERE CLAIM_ID = $CLAIM_ID
  AND DEFENDANT_ID = $DEFENDANT_ID
  AND IS_CURRENT = TRUE;

INSERT INTO MFQ_ANSWERS
(
    ANSWER_ID,
    CLAIM_ID,
    DEFENDANT_ID,
    QUESTION_ID,
    ANSWER_TEXT,
    ANSWER_JSON,
    CONFIDENCE_SCORE,
    STATUS,
    IS_CURRENT,
    CREATED_TS,
    LAST_UPDATED_TS
)
SELECT
    UUID_STRING(),
    $CLAIM_ID,
    $DEFENDANT_ID,
    q.QUESTION_ID,
    CASE
      WHEN q.ANSWER_TYPE = 'TEXT' THEN 'Auto-populated answer from Snowflake for this MFQ question.'
      WHEN q.ANSWER_TYPE IN ('YES_NO', 'YES_NO_UNCLEAR', 'YES_NO_UNCLEAR_NA', 'CHOICE', 'RATING_1_9', 'RATING_1_5')
        THEN IFF(ARRAY_SIZE(q.ALLOWED_VALUES) > 0, q.ALLOWED_VALUES[0]::STRING, 'YES')
      WHEN q.ANSWER_TYPE = 'MULTISELECT'
        THEN ARRAY_TO_STRING(IFF(ARRAY_SIZE(q.ALLOWED_VALUES) > 0, ARRAY_CONSTRUCT(q.ALLOWED_VALUES[0]::STRING), ARRAY_CONSTRUCT()), ', ')
      ELSE 'Auto-populated answer from Snowflake for this MFQ question.'
    END AS ANSWER_TEXT,
    CASE
      WHEN q.ANSWER_TYPE = 'TEXT'
        THEN OBJECT_CONSTRUCT('value', 'Auto-populated answer from Snowflake for this MFQ question.')
      WHEN q.ANSWER_TYPE IN ('YES_NO', 'YES_NO_UNCLEAR', 'YES_NO_UNCLEAR_NA', 'CHOICE', 'RATING_1_9', 'RATING_1_5')
        THEN OBJECT_CONSTRUCT('value', IFF(ARRAY_SIZE(q.ALLOWED_VALUES) > 0, q.ALLOWED_VALUES[0]::STRING, 'YES'))
      WHEN q.ANSWER_TYPE = 'MULTISELECT'
        THEN OBJECT_CONSTRUCT('value', IFF(ARRAY_SIZE(q.ALLOWED_VALUES) > 0, ARRAY_CONSTRUCT(q.ALLOWED_VALUES[0]::STRING), ARRAY_CONSTRUCT()))
      ELSE OBJECT_CONSTRUCT('value', 'Auto-populated answer from Snowflake for this MFQ question.')
    END AS ANSWER_JSON,
    0.92,
    'AI_GENERATED',
    TRUE,
    CURRENT_TIMESTAMP(),
    CURRENT_TIMESTAMP()
FROM MFQ_QUESTIONS q
WHERE q.FORM_KEY = 'MFQ_V1'
  AND q.IS_ACTIVE = TRUE
  AND q.IS_CURRENT = TRUE;
