USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

INSERT INTO MFQ_ROLES (ROLE_ID, ROLE_CODE, ROLE_NAME, IS_ACTIVE)
SELECT 'ROLE-ANALYST','CLAIMS_ANALYST','Claims Analyst',TRUE UNION ALL
SELECT 'ROLE-FACULTY','MEDICAL_FACULTY','Medical Faculty',TRUE UNION ALL
SELECT 'ROLE-ADVICE','ADVICE_TEAM','Advice Team',TRUE UNION ALL
SELECT 'ROLE-EXEC','EXECUTIVE','Executive',TRUE UNION ALL
SELECT 'ROLE-ADMIN','ADMIN','Admin',TRUE;

INSERT INTO MFQ_RBAC_ACCESS (ACCESS_ID, ROLE_ID, PERMISSION_CODE, PERMISSION_NAME, IS_ACTIVE)
SELECT 'RBA-001','ROLE-ANALYST','VIEW_CLAIMS','View Claims',TRUE UNION ALL
SELECT 'RBA-002','ROLE-ANALYST','ASSIGN_CLAIMS','Assign Claims',TRUE UNION ALL
SELECT 'RBA-003','ROLE-FACULTY','VIEW_CLAIMS','View Claims',TRUE UNION ALL
SELECT 'RBA-004','ROLE-ADVICE','VIEW_CLAIMS','View Claims',TRUE UNION ALL
SELECT 'RBA-005','ROLE-EXEC','VIEW_REPORTS','View Reports',TRUE UNION ALL
SELECT 'RBA-006','ROLE-ADMIN','MANAGE_USERS','Manage Users',TRUE;

INSERT INTO MFQ_USERS (USER_ID, USERNAME, EMAIL, DISPLAY_NAME, IS_ACTIVE)
SELECT 'USR-001','claims.analyst','claims.analyst@magmutual.demo','Casey Analyst',TRUE UNION ALL
SELECT 'USR-002','faculty.one','faculty.one@magmutual.demo','Dr. Jordan Faculty',TRUE UNION ALL
SELECT 'USR-003','advice.team','advice.team@magmutual.demo','Taylor Advice',TRUE UNION ALL
SELECT 'USR-004','executive.user','executive.user@magmutual.demo','Morgan Executive',TRUE UNION ALL
SELECT 'USR-005','portal.admin','portal.admin@magmutual.demo','Riley Admin',TRUE;

INSERT INTO MFQ_USER_ROLES (USER_ROLE_ID, USER_ID, ROLE_ID, IS_ACTIVE)
SELECT 'URO-001','USR-001','ROLE-ANALYST',TRUE UNION ALL
SELECT 'URO-002','USR-002','ROLE-FACULTY',TRUE UNION ALL
SELECT 'URO-003','USR-003','ROLE-ADVICE',TRUE UNION ALL
SELECT 'URO-004','USR-004','ROLE-EXEC',TRUE UNION ALL
SELECT 'URO-005','USR-005','ROLE-ADMIN',TRUE;

INSERT INTO MFQ_CLAIMS (CLAIM_ID, FILE_NUMBER, PATIENT_NAME, STATUS, PRIORITY, DATE_REQUESTED)
SELECT 'CLM-1001','MM-240001','A. Patient','MFQ Generated','High','2026-03-03'::DATE UNION ALL
SELECT 'CLM-1002','MM-240002','B. Patient','Assigned','Medium','2026-03-07'::DATE;

INSERT INTO MFQ_CLAIM_DEFENDANTS (DEFENDANT_ID, CLAIM_ID, DEFENDANT_NAME, SPECIALTY, BRIEF_SYNOPSIS, ALLEGED_INJURY_TERMS, ALLEGATION_SUMMARY)
SELECT 'DEF-1001','CLM-1001','Dr. Blake','Obstetrics & Gynecology','Labor and delivery review','Brachial plexus injury','Delayed C-section allegation' UNION ALL
SELECT 'DEF-1002','CLM-1002','Dr. Rivera','Emergency Medicine','ER sepsis timeline','Sepsis progression','Delayed diagnosis allegation';

INSERT INTO MFQ_ASSIGNMENTS (ASSIGNMENT_ID, CLAIM_ID, ASSIGNED_TO_USER_ID, ASSIGNED_BY_USER_ID, ASSIGNMENT_STATUS, PRIORITY)
SELECT 'ASG-001','CLM-1002','USR-002','USR-001','ACTIVE','Medium' UNION ALL
SELECT 'ASG-002','CLM-1001','USR-001','USR-005','ACTIVE','High';

INSERT INTO MFQ_PIPELINE_RUNS (RUN_ID, CLAIM_ID, DEFENDANT_ID, STATUS, AI_CONFIDENCE, STARTED_TS, COMPLETED_TS)
SELECT 'RUN-001','CLM-1001','DEF-1001','COMPLETED',0.93,'2026-03-03 10:00:00'::TIMESTAMP_LTZ,'2026-03-03 10:07:00'::TIMESTAMP_LTZ;

INSERT INTO MFQ_AI_CONFIDENCE (CONFIDENCE_ID, CLAIM_ID, DEFENDANT_ID, OVERALL_CONFIDENCE_SCORE)
SELECT 'AIC-001','CLM-1001','DEF-1001',0.93;

INSERT INTO MFQ_RECORD_SUMMARY (RECORD_SUMMARY_ID, CLAIM_ID, DEFENDANT_ID, SUMMARY_TEXT)
SELECT 'RS-001','CLM-1001','DEF-1001','Records indicate prolonged labor with evolving fetal distress.';
INSERT INTO MFQ_MEDCRON_SUMMARY (MEDCRON_SUMMARY_ID, CLAIM_ID, DEFENDANT_ID, SUMMARY_TEXT)
SELECT 'MS-001','CLM-1001','DEF-1001','Timeline: admission, labor progression, fetal decelerations, C-section.';
INSERT INTO MFQ_LEGAL_MEMO (LEGAL_MEMO_ID, CLAIM_ID, DEFENDANT_ID, SUMMARY_TEXT)
SELECT 'LM-001','CLM-1001','DEF-1001','Potential exposure centers on timing and escalation decisions.';

INSERT INTO MFQ_ANSWERS (ANSWER_ID, CLAIM_ID, DEFENDANT_ID, QUESTION_ID, ANSWER_TEXT, CONFIDENCE_SCORE, STATUS, IS_CURRENT)
SELECT 'ANS-001','CLM-1001','DEF-1001',QUESTION_ID,'YES',0.98,'GENERATED',TRUE
FROM MFQ_QUESTIONS WHERE QUESTION_KEY = 'S1_Q1' LIMIT 1;

INSERT INTO MFQ_QUESTION_CONFIDENCE (QUESTION_CONFIDENCE_ID, CLAIM_ID, DEFENDANT_ID, QUESTION_ID, CONFIDENCE_SCORE)
SELECT 'QC-001','CLM-1001','DEF-1001',QUESTION_ID,0.98
FROM MFQ_QUESTIONS WHERE QUESTION_KEY = 'S1_Q1' LIMIT 1;

INSERT INTO MFQ_NOTIFICATIONS (NOTIFICATION_ID, USER_ID, EVENT_TYPE, EVENT_TITLE, EVENT_MESSAGE, CLAIM_ID, EVENT_PRIORITY, IS_READ)
SELECT 'NTF-001','USR-001','CLAIM_READY','MFQ Generated','Claim CLM-1001 is ready for analyst review.','CLM-1001','INFO',FALSE;

INSERT INTO MFQ_DOCUMENTS (DOCUMENT_ID, CLAIM_ID, DEFENDANT_ID, FILE_NAME, DOC_TYPE, OCR_STATUS)
SELECT 'DOC-001','CLM-1001','DEF-1001','delivery_note.pdf','MEDICAL_RECORD','COMPLETED';

INSERT INTO MFQ_REPORTS (REPORT_ID, CLAIM_ID, REPORT_TYPE, REPORT_STATUS, REPORT_PAYLOAD)
SELECT 'RPT-001','CLM-1001','CLAIM_SUMMARY','READY',PARSE_JSON('{"format":"json"}');

INSERT INTO MFQ_AUDIT_LOG (AUDIT_ID, ENTITY_TYPE, ENTITY_ID, ACTION_TYPE, ACTOR_USER_ID)
SELECT 'AUD-001','CLAIM','CLM-1001','CREATE','USR-001';

INSERT INTO MFQ_STATUS_HISTORY (STATUS_HISTORY_ID, CLAIM_ID, DEFENDANT_ID, EVENT_TYPE, FROM_STATUS, TO_STATUS, EVENT_BY_USER_ID, EVENT_NOTE)
SELECT 'HIS-001','CLM-1001','DEF-1001','STATUS_CHANGE','New','MFQ Generated','USR-001','Initial generation complete.';
