USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

-- Replace claim id / defendant id as needed before running in non-demo environments.
SET CLAIM_ID = 'CLM-1001';
SET DEFENDANT_ID = (
  SELECT DEFENDANT_ID
  FROM MFQ_CLAIM_DEFENDANTS
  WHERE CLAIM_ID = $CLAIM_ID
  ORDER BY DEFENDANT_ID
  LIMIT 1
);

DELETE FROM MFQ_ANSWERS
WHERE CLAIM_ID = $CLAIM_ID
  AND DEFENDANT_ID = $DEFENDANT_ID;

INSERT INTO MFQ_ANSWERS (
  ANSWER_ID,
  CLAIM_ID,
  DEFENDANT_ID,
  QUESTION_ID,
  ANSWER_TEXT,
  ANSWER_JSON,
  CONFIDENCE_SCORE,
  STATUS,
  IS_CURRENT,
  CREATED_TS,
  LAST_UPDATED_TS
)
SELECT
  UUID_STRING(),
  $CLAIM_ID,
  $DEFENDANT_ID,
  q.QUESTION_ID,
  CASE
    WHEN q.ANSWER_TYPE IN ('YES_NO', 'YES_NO_UNCLEAR', 'YES_NO_UNCLEAR_NA', 'CHOICE', 'RATING_1_9', 'RATING_1_5')
      THEN IFF(ARRAY_SIZE(q.ALLOWED_VALUES) > 0, q.ALLOWED_VALUES[0]::STRING, NULL)
    WHEN q.ANSWER_TYPE = 'MULTISELECT'
      THEN NULL
    ELSE CONCAT('Sample answer for ', q.QUESTION_KEY)
  END AS ANSWER_TEXT,
  CASE
    WHEN q.ANSWER_TYPE = 'MULTISELECT'
      THEN IFF(ARRAY_SIZE(q.ALLOWED_VALUES) > 0, ARRAY_CONSTRUCT(q.ALLOWED_VALUES[0]::STRING), ARRAY_CONSTRUCT())
    ELSE NULL
  END AS ANSWER_JSON,
  0.82,
  'GENERATED',
  TRUE,
  CURRENT_TIMESTAMP(),
  CURRENT_TIMESTAMP()
FROM MFQ_QUESTIONS q
WHERE q.FORM_KEY = 'MFQ_V1'
  AND q.IS_ACTIVE = TRUE
  AND q.IS_CURRENT = TRUE;
