USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

SELECT COUNT(*) FROM MFQ_CLAIMS;
SELECT COUNT(*) FROM MFQ_SECTIONS;
SELECT COUNT(*) FROM MFQ_QUESTIONS;
SELECT COUNT(*) FROM MFQ_ANSWERS;
SELECT COUNT(*) FROM MFQ_ASSIGNMENTS;
SELECT COUNT(*) FROM MFQ_ASSIGNMENT_SECTIONS;
SELECT COUNT(*) FROM MFQ_NOTIFICATIONS;
SELECT COUNT(*) FROM MFQ_RECORD_SUMMARY;
SELECT COUNT(*) FROM MFQ_MEDCRON_SUMMARY;
SELECT COUNT(*) FROM MFQ_LEGAL_MEMO;
SELECT COUNT(*) FROM MFQ_DOCUMENTS;
SELECT COUNT(*) FROM MFQ_REPORTS;
SELECT COUNT(*) FROM MFQ_AUDIT_LOG;
SELECT COUNT(*) FROM MFQ_STATUS_HISTORY;

SELECT
    S.SECTION_KEY,
    S.SECTION_NAME,
    Q.QUESTION_KEY,
    Q.QUESTION_TEXT,
    Q.ANSWER_TYPE
FROM MFQ_SECTIONS S
JOIN MFQ_QUESTIONS Q
    ON S.SECTION_ID = Q.SECTION_ID
WHERE S.FORM_KEY = 'MFQ_V1'
ORDER BY S.DISPLAY_ORDER, Q.DISPLAY_ORDER;
