USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

SELECT COUNT(*) AS TOTAL_MFQ_QUESTIONS
FROM MFQ_QUESTIONS
WHERE FORM_KEY = 'MFQ_V1'
  AND IS_ACTIVE = TRUE
  AND IS_CURRENT = TRUE;

SELECT COUNT(*) AS TOTAL_AUTO_POPULATED_ANSWERS
FROM MFQ_ANSWERS
WHERE CLAIM_ID = 'CLM-1002'
  AND IS_CURRENT = TRUE;

SELECT
    s.SECTION_NAME,
    q.QUESTION_KEY,
    q.QUESTION_TEXT,
    q.ANSWER_TYPE,
    a.ANSWER_TEXT,
    a.ANSWER_JSON,
    a.CONFIDENCE_SCORE
FROM MFQ_SECTIONS s
JOIN MFQ_QUESTIONS q
    ON q.SECTION_ID = s.SECTION_ID
LEFT JOIN MFQ_ANSWERS a
    ON a.QUESTION_ID = q.QUESTION_ID
   AND a.CLAIM_ID = 'CLM-1002'
   AND a.IS_CURRENT = TRUE
WHERE s.FORM_KEY = 'MFQ_V1'
ORDER BY s.DISPLAY_ORDER, q.DISPLAY_ORDER;
