USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

SELECT COUNT(*) AS SECTION_COUNT
FROM MFQ_SECTIONS
WHERE FORM_KEY = 'MFQ_V1';

SELECT COUNT(*) AS QUESTION_COUNT
FROM MFQ_QUESTIONS
WHERE FORM_KEY = 'MFQ_V1';

SELECT
    s.DISPLAY_ORDER AS SECTION_ORDER,
    s.SECTION_NAME,
    q.DISPLAY_ORDER AS QUESTION_ORDER,
    q.QUESTION_KEY,
    q.QUESTION_TEXT,
    q.ANSWER_TYPE
FROM MFQ_SECTIONS s
JOIN MFQ_QUESTIONS q
    ON s.SECTION_ID = q.SECTION_ID
WHERE s.FORM_KEY = 'MFQ_V1'
ORDER BY s.DISPLAY_ORDER, q.DISPLAY_ORDER;
