CREATE OR REPLACE STAGE MAGMUTUAL_MFQ_APP.PUBLIC.MFQ_APP_STAGE;

CREATE OR REPLACE STREAMLIT MAGMUTUAL_MFQ_APP.PUBLIC.MFQ_V1
  ROOT_LOCATION = '@MAGMUTUAL_MFQ_APP.PUBLIC.MFQ_APP_STAGE'
  MAIN_FILE = '/O10X860A1C1RC41Z/streamlit_app.py'
  QUERY_WAREHOUSE = COMPUTE_WH;
