USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

-- Session context is fixed for this portal deployment.
SELECT CURRENT_ROLE() AS ACTIVE_ROLE,
       CURRENT_WAREHOUSE() AS ACTIVE_WAREHOUSE,
       CURRENT_DATABASE() AS ACTIVE_DATABASE,
       CURRENT_SCHEMA() AS ACTIVE_SCHEMA;
