USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE CLAIM (
  CLAIM_ID STRING NOT NULL,
  FILE_NUMBER STRING NOT NULL,
  PATIENT_NAME STRING,
  CLAIM_STATUS STRING DEFAULT 'MFQ Generated',
  PRIORITY STRING DEFAULT 'Medium',
  DATE_REQUESTED DATE,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (CLAIM_ID)
);

CREATE OR REPLACE TABLE CLAIM_DEFENDANT (
  DEFENDANT_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_NAME STRING NOT NULL,
  SPECIALTY STRING,
  BRIEF_SYNOPSIS STRING,
  ALLEGED_INJURY_TERMS STRING,
  ALLEGATION_SUMMARY STRING,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (DEFENDANT_ID)
);

CREATE OR REPLACE TABLE PIPELINE_RUN (
  RUN_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING NOT NULL,
  STATUS STRING NOT NULL,
  AI_CONFIDENCE FLOAT,
  STARTED_TS TIMESTAMP_LTZ,
  COMPLETED_TS TIMESTAMP_LTZ,
  PRIMARY KEY (RUN_ID)
);

CREATE OR REPLACE TABLE MFQ_SECTIONS (
  SECTION_ID STRING NOT NULL,
  FORM_KEY STRING NOT NULL,
  SECTION_KEY STRING NOT NULL,
  SECTION_NAME STRING NOT NULL,
  SECTION_ORDER NUMBER NOT NULL,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (SECTION_ID)
);

CREATE OR REPLACE TABLE MFQ_QUESTIONS (
  QUESTION_ID STRING NOT NULL,
  FORM_KEY STRING NOT NULL,
  SECTION_ID STRING NOT NULL,
  QUESTION_KEY STRING NOT NULL,
  QUESTION_TEXT STRING NOT NULL,
  QUESTION_ORDER NUMBER NOT NULL,
  ANSWER_TYPE STRING NOT NULL,
  ALLOWED_VALUES VARIANT,
  IS_CURRENT BOOLEAN DEFAULT TRUE,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (QUESTION_ID)
);

CREATE OR REPLACE TABLE MFQ_ANSWER (
  ANSWER_ID STRING NOT NULL,
  DEFENDANT_ID STRING NOT NULL,
  QUESTION_ID STRING NOT NULL,
  ANSWER_TEXT STRING,
  ANSWER_JSON VARIANT,
  CONFIDENCE_SCORE FLOAT,
  STATUS STRING DEFAULT 'GENERATED',
  IS_CURRENT BOOLEAN DEFAULT TRUE,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ANSWER_ID)
);

CREATE OR REPLACE TABLE HUMAN_REVIEW (
  REVIEW_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING,
  REVIEWER_USER_ID STRING,
  REVIEW_STATUS STRING,
  REVIEW_NOTES STRING,
  REVIEW_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (REVIEW_ID)
);

CREATE OR REPLACE TABLE CLAIM_SUMMARY (
  SUMMARY_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING,
  SUMMARY_TYPE STRING,
  SUMMARY_TEXT STRING,
  GENERATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (SUMMARY_ID)
);

CREATE OR REPLACE TABLE DOCUMENT_OCR_RESULTS (
  OCR_RESULT_ID STRING NOT NULL,
  CLAIM_ID STRING,
  DEFENDANT_ID STRING,
  FILE_NAME STRING,
  OCR_TEXT STRING,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (OCR_RESULT_ID)
);

CREATE OR REPLACE TABLE DOCUMENT_SENTENCES (
  SENTENCE_ID STRING NOT NULL,
  CLAIM_ID STRING,
  DEFENDANT_ID STRING,
  FILE_NAME STRING,
  SENTENCE_TEXT STRING,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (SENTENCE_ID)
);

CREATE OR REPLACE TABLE COMBINED_TABLE_INDEX (
  INDEX_ID STRING NOT NULL,
  CLAIM_ID STRING,
  DEFENDANT_ID STRING,
  FILE_NAME STRING,
  SOURCE_TABLE STRING,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (INDEX_ID)
);

CREATE OR REPLACE VIEW QST_SECTION AS SELECT * FROM MFQ_SECTIONS;
CREATE OR REPLACE VIEW QST_QUESTION AS SELECT * FROM MFQ_QUESTIONS;
