BEGIN
  CREATE DATABASE IF NOT EXISTS IDENTIFIER($APP_DB);
  CREATE SCHEMA IF NOT EXISTS IDENTIFIER($APP_DB || '.' || $APP_SCHEMA);
  CREATE STAGE IF NOT EXISTS IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.' || $APP_STAGE);
END;


CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.PIPELINE_CONFIG') (
    CONFIG_KEY STRING NOT NULL,
    CONFIG_VALUE STRING,
    DATA_TYPE STRING NOT NULL,
    DESCRIPTION STRING,
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CONFIG_KEY)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_CONFIG') (
    MODEL_KEY STRING NOT NULL,
    PROVIDER STRING NOT NULL,
    ENDPOINT_URL STRING,
    SECRET_NAME STRING,
    TEMPERATURE FLOAT,
    MAX_TOKENS NUMBER,
    ADDITIONAL_PARAMETERS VARIANT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MODEL_KEY)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_ROUTING') (
    ROUTE_KEY STRING NOT NULL,
    TASK_TYPE STRING NOT NULL,
    SECTION_KEY STRING,
    QUESTION_KEY STRING,
    GENERATION_MODEL_KEY STRING NOT NULL,
    EVALUATION_MODEL_KEY STRING NOT NULL,
    EMBEDDING_MODEL_KEY STRING,
    PRIORITY NUMBER DEFAULT 100,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ROUTE_KEY)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.WORKFLOW_STATUS_DEF') (
    ENTITY_TYPE STRING NOT NULL,
    STATUS_CODE STRING NOT NULL,
    ALLOWED_NEXT VARIANT,
    DESCRIPTION STRING,
    PRIMARY KEY (ENTITY_TYPE, STATUS_CODE)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.PROMPT_TEMPLATE') (
    TEMPLATE_ID STRING DEFAULT UUID_STRING(),
    TEMPLATE_KEY STRING NOT NULL,
    QUESTION_KEY STRING,
    TEMPLATE_TYPE STRING NOT NULL,
    TEMPLATE_VERSION NUMBER NOT NULL DEFAULT 1,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    DESCRIPTION STRING,
    PROMPT_TEXT STRING NOT NULL,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TEMPLATE_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.PROMPT_TEMPLATE_HISTORY') (
    HISTORY_ID STRING DEFAULT UUID_STRING(),
    TEMPLATE_KEY STRING NOT NULL,
    QUESTION_KEY STRING,
    OLD_PROMPT_TEXT STRING,
    NEW_PROMPT_TEXT STRING,
    CHANGED_BY STRING,
    CHANGED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    CHANGE_NOTE STRING,
    PRIMARY KEY (HISTORY_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.QST_SECTION') (
    SECTION_ID STRING DEFAULT UUID_STRING(),
    FORM_KEY STRING NOT NULL,
    SECTION_KEY STRING NOT NULL,
    SECTION_NAME STRING NOT NULL,
    DISPLAY_ORDER NUMBER NOT NULL,
    IS_SKIPPABLE BOOLEAN DEFAULT FALSE,
    SKIP_CONDITION VARIANT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SECTION_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.QST_QUESTION') (
    QUESTION_ID STRING DEFAULT UUID_STRING(),
    FORM_KEY STRING NOT NULL,
    SECTION_ID STRING NOT NULL,
    QUESTION_KEY STRING NOT NULL,
    PARENT_QUESTION_ID STRING,
    DISPLAY_ORDER NUMBER NOT NULL,
    QUESTION_VERSION NUMBER DEFAULT 1,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    STATUS STRING DEFAULT 'ACTIVE',
    PROMPT_TEMPLATE_KEY STRING,
    QUESTION_TEXT STRING NOT NULL,
    ANSWER_TYPE STRING NOT NULL,
    ALLOWED_VALUES VARIANT,
    VISIBILITY_RULE VARIANT,
    SEARCH_TOP_K NUMBER,
    SEARCH_DOC_TYPE_FILTER VARIANT,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (QUESTION_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.SUMMARY_CONFIG') (
    SUMMARY_TYPE STRING NOT NULL,
    DISPLAY_ORDER NUMBER NOT NULL,
    SECTION_KEYS VARIANT,
    SEARCH_QUERY STRING,
    WORD_TARGET NUMBER,
    INSTRUCTIONS STRING,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    PRIMARY KEY (SUMMARY_TYPE)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM') (
    CLAIM_ID STRING NOT NULL,
    FILE_NUMBER STRING NOT NULL,
    PATIENT_NAME STRING,
    STATUS STRING DEFAULT 'ACTIVE',
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CLAIM_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_DEFENDANT') (
    DEFENDANT_ID STRING NOT NULL,
    CLAIM_ID STRING NOT NULL,
    DEFENDANT_NAME STRING NOT NULL,
    DEFENDANT_SPECIALTY STRING,
    PIPELINE_STATUS STRING DEFAULT 'PENDING',
    BRIEF_SYNOPSIS STRING,
    ALLEGED_INJURY_TERMS STRING,
    ALLEGATION_SUMMARY STRING,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (DEFENDANT_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.PIPELINE_RUN') (
    RUN_ID STRING NOT NULL,
    CLAIM_ID STRING NOT NULL,
    DEFENDANT_ID STRING NOT NULL,
    RUN_TYPE STRING NOT NULL,
    GENERATION_MODEL_KEY STRING,
    EVALUATION_MODEL_KEY STRING,
    STATUS STRING NOT NULL,
    REQUESTED_COMPONENTS VARIANT,
    REQUESTED_BY STRING,
    STARTED_AT TIMESTAMP_LTZ NOT NULL,
    COMPLETED_AT TIMESTAMP_LTZ,
    DURATION_SECONDS NUMBER,
    PHASE_STATUSES VARIANT,
    ERROR_MESSAGE STRING,
    PRIMARY KEY (RUN_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_COMPONENT_STATUS') (
    RUN_ID STRING NOT NULL,
    DEFENDANT_ID STRING NOT NULL,
    COMPONENT_TYPE STRING NOT NULL,
    COMPONENT_KEY STRING NOT NULL,
    STATUS STRING NOT NULL,
    UPDATED_AT TIMESTAMP_LTZ NOT NULL,
    DETAILS VARIANT,
    PRIMARY KEY (RUN_ID, DEFENDANT_ID, COMPONENT_TYPE, COMPONENT_KEY)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.PIPELINE_AUDIT_EVENT') (
    EVENT_ID STRING DEFAULT UUID_STRING(),
    EVENT_TS TIMESTAMP_LTZ NOT NULL,
    RUN_ID STRING,
    ENTITY_TYPE STRING NOT NULL,
    ENTITY_ID STRING NOT NULL,
    ACTION STRING NOT NULL,
    LEVEL STRING,
    CHANGED_BY STRING,
    TASK_REF STRING,
    MESSAGE STRING,
    PAYLOAD VARIANT,
    PRIMARY KEY (EVENT_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.AGENT_STEP_LOG') (
    STEP_ID STRING DEFAULT UUID_STRING(),
    RUN_ID STRING NOT NULL,
    AGENT_TYPE STRING NOT NULL,
    TASK_REF STRING NOT NULL,
    STEP_NUMBER NUMBER NOT NULL,
    STEP_TYPE STRING NOT NULL,
    STEP_TS TIMESTAMP_LTZ NOT NULL,
    CONTENT STRING,
    PAYLOAD VARIANT,
    PRIMARY KEY (STEP_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.DOCUMENT_SENTENCE_EMBEDDINGS') (
    EMBEDDING_ID STRING NOT NULL,
    FILE_NAME STRING NOT NULL,
    SENTENCE_ID NUMBER NOT NULL,
    SENTENCE_TEXT STRING,
    EMBEDDING_MODEL_KEY STRING NOT NULL,
    EMBEDDING_VECTOR VECTOR(FLOAT, 1024),
    EMBED_STATUS STRING DEFAULT 'EMBEDDED',
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EMBEDDING_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CHRONOLOGY_EVENT') (
    EVENT_ID STRING NOT NULL,
    RUN_ID STRING NOT NULL,
    DEFENDANT_ID STRING NOT NULL,
    GEN_VERSION NUMBER NOT NULL,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    EVENT_SEQUENCE NUMBER NOT NULL,
    EVENT_DATE DATE,
    EVENT_TYPE STRING,
    EVENT_DESCRIPTION STRING,
    IS_KEY_EVENT BOOLEAN DEFAULT FALSE,
    SOURCE_SENTENCES VARIANT,
    LLM_MODEL_KEY STRING,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EVENT_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.GAP_HYPOTHESIS') (
    HYPOTHESIS_ID STRING NOT NULL,
    RUN_ID STRING NOT NULL,
    DEFENDANT_ID STRING NOT NULL,
    RUN_VERSION NUMBER NOT NULL,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    EXPECTED_DOC_TYPE STRING,
    EXPECTED_LABEL STRING,
    EXPECTED_TIMEFRAME STRING,
    CLINICAL_RATIONALE STRING,
    PROTOCOL_REFERENCE STRING,
    SIGNIFICANCE STRING,
    SEARCH_QUERIES VARIANT,
    TARGET_DOC_TYPES VARIANT,
    LLM_MODEL_KEY STRING,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (HYPOTHESIS_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.GAP_FINDING') (
    FINDING_ID STRING NOT NULL,
    HYPOTHESIS_ID STRING NOT NULL,
    STATUS STRING NOT NULL,
    CONFIDENCE_SCORE FLOAT,
    FOUND_IN_FILES VARIANT,
    GAP_DESCRIPTION STRING,
    CLINICAL_IMPACT STRING,
    LEGAL_IMPACT STRING,
    RECOMMENDATION STRING,
    EVAL_SIGNIFICANCE STRING,
    EVAL_NOTES STRING,
    LLM_MODEL_KEY STRING,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (FINDING_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_ANSWER') (
    ANSWER_ID STRING NOT NULL,
    RUN_ID STRING NOT NULL,
    DEFENDANT_ID STRING NOT NULL,
    QUESTION_ID STRING NOT NULL,
    QUESTION_KEY STRING NOT NULL,
    ANSWER_VERSION NUMBER NOT NULL,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    ANSWER_RAW STRING,
    ANSWER_TEXT STRING,
    ANSWER_RATING NUMBER,
    ANSWER_MULTISELECT VARIANT,
    LLM_MODEL_KEY STRING,
    EVAL_MODEL_KEY STRING,
    PROMPT_RENDERED STRING,
    SOURCE_SENTENCES VARIANT,
    CONFIDENCE_SCORE FLOAT,
    RETRIEVAL_CORRECTED BOOLEAN DEFAULT FALSE,
    STATUS STRING DEFAULT 'GENERATED',
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ANSWER_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_EVALUATION') (
    EVALUATION_ID STRING NOT NULL,
    ENTITY_TYPE STRING NOT NULL,
    ENTITY_ID STRING NOT NULL,
    GENERATION_MODEL_KEY STRING,
    EVALUATION_MODEL_KEY STRING,
    FAITHFULNESS_SCORE FLOAT,
    RELEVANCE_SCORE FLOAT,
    COMPLETENESS_SCORE FLOAT,
    CONSISTENCY_SCORE FLOAT,
    HALLUCINATION_RISK FLOAT,
    HALLUCINATION_FLAG BOOLEAN,
    CONSTRAINED_VALID BOOLEAN,
    NEEDS_HUMAN_REVIEW BOOLEAN,
    EVAL_RATIONALE STRING,
    RAW_RESULT VARIANT,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EVALUATION_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_SUMMARY') (
    SUMMARY_ID STRING NOT NULL,
    RUN_ID STRING NOT NULL,
    DEFENDANT_ID STRING NOT NULL,
    SUMMARY_TYPE STRING NOT NULL,
    SUMMARY_VERSION NUMBER NOT NULL,
    IS_CURRENT BOOLEAN DEFAULT TRUE,
    SUMMARY_TEXT STRING,
    KEY_FINDINGS VARIANT,
    DEVIATIONS_NOTED VARIANT,
    WORD_COUNT NUMBER,
    COMPLETENESS_FLAG BOOLEAN,
    MISSING_INFO_NOTES STRING,
    LLM_MODEL_KEY STRING,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (SUMMARY_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.HUMAN_REVIEW') (
    REVIEW_ID STRING NOT NULL,
    ENTITY_TYPE STRING NOT NULL,
    ENTITY_ID STRING NOT NULL,
    REVIEWER_ID STRING,
    REVIEW_STATUS STRING NOT NULL,
    REVIEW_REASON STRING,
    REQUESTED_BY STRING,
    OVERRIDE_PAYLOAD VARIANT,
    REQUESTED_REGEN BOOLEAN DEFAULT FALSE,
    REGEN_MODEL_KEY STRING,
    REGEN_EVAL_MODEL_KEY STRING,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (REVIEW_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.REGENERATION_LOG') (
    REGENERATION_ID STRING NOT NULL,
    ENTITY_TYPE STRING NOT NULL,
    ORIGINAL_ENTITY_ID STRING NOT NULL,
    NEW_ENTITY_ID STRING,
    GENERATION_MODEL_KEY STRING,
    EVALUATION_MODEL_KEY STRING,
    STATUS STRING,
    REASON STRING,
    REQUESTED_BY STRING,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (REGENERATION_ID)
);
