CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.VW_OCR_CLAIM_SOURCE') AS
SELECT
    i.FILE_NUMBER,
    i.FILE_NAME,
    i.FOLDER_NAME,
    i.DOC_TYPE_NAME,
    i.DOCUMENT_TYPE_DESCRIPTION,
    i.DOCUMENT_DATE,
    i.DOCUMENT_ID,
    i.SEQUENCE_NUMBER,
    i.UNC_PATH,
    r.FILE_STATUS,
    r.PROCESSED_AT,
    r.MFQ_QA_STATUS
FROM IDENTIFIER($SOURCE_DB || '.' || $SOURCE_SCHEMA || '.' || $SOURCE_COMBINED_TABLE_INDEX) i
LEFT JOIN IDENTIFIER($SOURCE_DB || '.' || $SOURCE_SCHEMA || '.' || $SOURCE_DOCUMENT_OCR_RESULTS) r
  ON i.FILE_NAME = r.FILE_NAME;

CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.VW_OCR_CLAIM_SENTENCES') AS
SELECT
    i.FILE_NUMBER,
    i.FILE_NAME,
    i.DOC_TYPE_NAME,
    i.DOCUMENT_DATE,
    s.SENTENCE_ID,
    s.SENTENCE
FROM IDENTIFIER($SOURCE_DB || '.' || $SOURCE_SCHEMA || '.' || $SOURCE_COMBINED_TABLE_INDEX) i
JOIN IDENTIFIER($SOURCE_DB || '.' || $SOURCE_SCHEMA || '.' || $SOURCE_DOCUMENT_SENTENCES) s
  ON i.FILE_NAME = s.FILE_NAME;

CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.VW_CURRENT_ANSWERS') AS
SELECT *
FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_ANSWER')
WHERE IS_CURRENT = TRUE;

CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.VW_PENDING_REVIEWS') AS
SELECT
    hr.REVIEW_ID,
    hr.ENTITY_TYPE,
    hr.ENTITY_ID,
    hr.REVIEW_STATUS,
    hr.REVIEWER_ID,
    ev.FAITHFULNESS_SCORE,
    ev.HALLUCINATION_FLAG,
    ev.NEEDS_HUMAN_REVIEW,
    hr.CREATED_AT
FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.HUMAN_REVIEW') hr
LEFT JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_EVALUATION') ev
  ON hr.ENTITY_ID = ev.ENTITY_ID
WHERE hr.REVIEW_STATUS = 'PENDING';
