USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

ALTER TABLE IF EXISTS COMBINED_TABLE_INDEX ADD COLUMN IF NOT EXISTS FILE_NUMBER STRING;
ALTER TABLE IF EXISTS COMBINED_TABLE_INDEX ADD COLUMN IF NOT EXISTS FOLDER_NAME STRING;
ALTER TABLE IF EXISTS COMBINED_TABLE_INDEX ADD COLUMN IF NOT EXISTS DOC_TYPE_NAME STRING;
ALTER TABLE IF EXISTS COMBINED_TABLE_INDEX ADD COLUMN IF NOT EXISTS DOCUMENT_TYPE_DESCRIPTION STRING;
ALTER TABLE IF EXISTS COMBINED_TABLE_INDEX ADD COLUMN IF NOT EXISTS DOCUMENT_DATE DATE;
ALTER TABLE IF EXISTS COMBINED_TABLE_INDEX ADD COLUMN IF NOT EXISTS DOCUMENT_ID STRING;
ALTER TABLE IF EXISTS COMBINED_TABLE_INDEX ADD COLUMN IF NOT EXISTS SEQUENCE_NUMBER NUMBER;
ALTER TABLE IF EXISTS COMBINED_TABLE_INDEX ADD COLUMN IF NOT EXISTS UNC_PATH STRING;

ALTER TABLE IF EXISTS DOCUMENT_OCR_RESULTS ADD COLUMN IF NOT EXISTS FILE_STATUS STRING;
ALTER TABLE IF EXISTS DOCUMENT_OCR_RESULTS ADD COLUMN IF NOT EXISTS PROCESSED_AT TIMESTAMP_LTZ;
ALTER TABLE IF EXISTS DOCUMENT_OCR_RESULTS ADD COLUMN IF NOT EXISTS MFQ_QA_STATUS STRING;

ALTER TABLE IF EXISTS DOCUMENT_SENTENCES ADD COLUMN IF NOT EXISTS SENTENCE STRING;

ALTER TABLE IF EXISTS HUMAN_REVIEW ADD COLUMN IF NOT EXISTS ENTITY_TYPE STRING;
ALTER TABLE IF EXISTS HUMAN_REVIEW ADD COLUMN IF NOT EXISTS ENTITY_ID STRING;
ALTER TABLE IF EXISTS HUMAN_REVIEW ADD COLUMN IF NOT EXISTS REVIEWER_ID STRING;
ALTER TABLE IF EXISTS HUMAN_REVIEW ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP();

CREATE TABLE IF NOT EXISTS LLM_EVALUATION (
  EVALUATION_ID STRING,
  ENTITY_ID STRING,
  FAITHFULNESS_SCORE FLOAT,
  HALLUCINATION_FLAG BOOLEAN,
  NEEDS_HUMAN_REVIEW BOOLEAN,
  CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

ALTER TABLE IF EXISTS LLM_EVALUATION ADD COLUMN IF NOT EXISTS ENTITY_ID STRING;
ALTER TABLE IF EXISTS LLM_EVALUATION ADD COLUMN IF NOT EXISTS FAITHFULNESS_SCORE FLOAT;
ALTER TABLE IF EXISTS LLM_EVALUATION ADD COLUMN IF NOT EXISTS HALLUCINATION_FLAG BOOLEAN;
ALTER TABLE IF EXISTS LLM_EVALUATION ADD COLUMN IF NOT EXISTS NEEDS_HUMAN_REVIEW BOOLEAN;
ALTER TABLE IF EXISTS LLM_EVALUATION ADD COLUMN IF NOT EXISTS CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP();

CREATE OR REPLACE VIEW VW_OCR_CLAIM_SOURCE AS
SELECT
    i.FILE_NUMBER,
    i.FILE_NAME,
    i.FOLDER_NAME,
    i.DOC_TYPE_NAME,
    i.DOCUMENT_TYPE_DESCRIPTION,
    i.DOCUMENT_DATE,
    i.DOCUMENT_ID,
    i.SEQUENCE_NUMBER,
    i.UNC_PATH,
    r.FILE_STATUS,
    r.PROCESSED_AT,
    r.MFQ_QA_STATUS
FROM COMBINED_TABLE_INDEX i
LEFT JOIN DOCUMENT_OCR_RESULTS r
  ON i.FILE_NAME = r.FILE_NAME;

CREATE OR REPLACE VIEW VW_OCR_CLAIM_SENTENCES AS
SELECT
    i.FILE_NUMBER,
    i.FILE_NAME,
    i.DOC_TYPE_NAME,
    i.DOCUMENT_DATE,
    s.SENTENCE_ID,
    s.SENTENCE
FROM COMBINED_TABLE_INDEX i
JOIN DOCUMENT_SENTENCES s
  ON i.FILE_NAME = s.FILE_NAME;

CREATE OR REPLACE VIEW VW_CURRENT_ANSWERS AS
SELECT *
FROM MFQ_ANSWER
WHERE IS_CURRENT = TRUE;

CREATE OR REPLACE VIEW VW_PENDING_REVIEWS AS
SELECT
    hr.REVIEW_ID,
    hr.ENTITY_TYPE,
    hr.ENTITY_ID,
    hr.REVIEW_STATUS,
    hr.REVIEWER_ID,
    ev.FAITHFULNESS_SCORE,
    ev.HALLUCINATION_FLAG,
    ev.NEEDS_HUMAN_REVIEW,
    hr.CREATED_AT AS REVIEW_CREATED_AT,
    ev.CREATED_AT AS EVALUATION_CREATED_AT,
    hr.CREATED_AT AS CREATED_AT
FROM HUMAN_REVIEW hr
LEFT JOIN LLM_EVALUATION ev
  ON hr.ENTITY_ID = ev.ENTITY_ID
WHERE hr.REVIEW_STATUS = 'PENDING';
