-- UI portal compatibility objects used by the Streamlit app.
-- Depends on 00_session_context.sql and 01_create_core_objects.sql.

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_CLAIMS') (
    CLAIM_ID STRING NOT NULL,
    FILE_NUMBER STRING,
    PATIENT_NAME STRING,
    DEFENDANT_NAME STRING,
    SPECIALTY STRING,
    CONTACT_DETAILS STRING,
    DATE_REQUESTED DATE,
    STATUS STRING,
    PRIORITY STRING,
    AI_CONFIDENCE FLOAT,
    HAS_NEW_MFQ_VERSION BOOLEAN DEFAULT FALSE,
    ASSIGNED_TO STRING,
    APPROVED_BY STRING,
    RECORDS_SUMMARY STRING,
    MEDCRON_TEXT STRING,
    LEGAL_MEMO_TEXT STRING,
    LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CLAIM_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_SECTIONS') (
    QUESTION_ID STRING DEFAULT UUID_STRING(),
    CLAIM_ID STRING NOT NULL,
    SECTION_NAME STRING NOT NULL,
    SECTION_ORDER NUMBER NOT NULL,
    QUESTION_ORDER NUMBER NOT NULL,
    QUESTION_TEXT STRING NOT NULL,
    ANSWER_TEXT STRING,
    SECTION_CONFIDENCE FLOAT DEFAULT 0,
    AI_CONFIDENCE FLOAT DEFAULT 0,
    IS_EDITABLE BOOLEAN DEFAULT TRUE,
    LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (QUESTION_ID)
);

CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_CLAIMS_VW') AS
SELECT
    CLAIM_ID,
    FILE_NUMBER,
    PATIENT_NAME,
    DEFENDANT_NAME,
    SPECIALTY,
    CONTACT_DETAILS,
    DATE_REQUESTED,
    STATUS,
    PRIORITY,
    AI_CONFIDENCE,
    HAS_NEW_MFQ_VERSION,
    ASSIGNED_TO,
    APPROVED_BY,
    RECORDS_SUMMARY,
    MEDCRON_TEXT,
    LEGAL_MEMO_TEXT,
    LAST_UPDATED_TS
FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_CLAIMS');
