USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

DELETE FROM MFQ_QUESTIONS WHERE FORM_KEY = 'MFQ_V1';
DELETE FROM MFQ_SECTIONS WHERE FORM_KEY = 'MFQ_V1';

INSERT INTO MFQ_SECTIONS (SECTION_ID, FORM_KEY, SECTION_KEY, SECTION_NAME, SECTION_ORDER, IS_ACTIVE)
SELECT 'SEC-001','MFQ_V1','SEC_COVER','Claim Information',1,TRUE UNION ALL
SELECT 'SEC-002','MFQ_V1','SEC_I','Overview and Timeline of Key Points',2,TRUE UNION ALL
SELECT 'SEC-003','MFQ_V1','SEC_II','Standard of Care and Causation',3,TRUE UNION ALL
SELECT 'SEC-004','MFQ_V1','SEC_III','Damages and Prognosis',4,TRUE UNION ALL
SELECT 'SEC-005','MFQ_V1','SEC_IV','Final Opinions',5,TRUE;

INSERT INTO MFQ_QUESTIONS (
  QUESTION_ID, FORM_KEY, SECTION_ID, QUESTION_KEY, QUESTION_TEXT, QUESTION_ORDER, ANSWER_TYPE, ALLOWED_VALUES, IS_CURRENT, IS_ACTIVE
)
SELECT 'Q-001','MFQ_V1','SEC-001','COVER_MAG_FILE','MagMutual File #',1,'TEXT',NULL,TRUE,TRUE UNION ALL
SELECT 'Q-002','MFQ_V1','SEC-001','COVER_PATIENT_NAME','Patient Name',2,'TEXT',NULL,TRUE,TRUE UNION ALL
SELECT 'Q-003','MFQ_V1','SEC-001','COVER_DEFENDANT_NAME','Defendant Name',3,'TEXT',NULL,TRUE,TRUE UNION ALL
SELECT 'Q-004','MFQ_V1','SEC-001','COVER_DEFENDANT_SPECIALTY','Defendant Specialty',4,'TEXT',NULL,TRUE,TRUE UNION ALL
SELECT 'Q-005','MFQ_V1','SEC-002','S1_Q1','Were all records needed for review received?',1,'YES_NO',PARSE_JSON('["YES","NO"]'),TRUE,TRUE UNION ALL
SELECT 'Q-006','MFQ_V1','SEC-002','S1_Q2','Summarize timeline of key medical events.',2,'LONG_TEXT',NULL,TRUE,TRUE UNION ALL
SELECT 'Q-007','MFQ_V1','SEC-003','S2_Q1','Did the care meet standard of care?',1,'YES_NO',PARSE_JSON('["YES","NO"]'),TRUE,TRUE UNION ALL
SELECT 'Q-008','MFQ_V1','SEC-003','S2_Q2','Explain deviations from standard of care.',2,'LONG_TEXT',NULL,TRUE,TRUE UNION ALL
SELECT 'Q-009','MFQ_V1','SEC-003','S2_Q3','Did any deviation cause injury?',3,'YES_NO',PARSE_JSON('["YES","NO"]'),TRUE,TRUE UNION ALL
SELECT 'Q-010','MFQ_V1','SEC-004','S3_Q1','Identify alleged damages and severity.',1,'LONG_TEXT',NULL,TRUE,TRUE UNION ALL
SELECT 'Q-011','MFQ_V1','SEC-004','S3_Q2','Describe expected prognosis and future care.',2,'LONG_TEXT',NULL,TRUE,TRUE UNION ALL
SELECT 'Q-012','MFQ_V1','SEC-005','S4_Q1','Provide final faculty opinion.',1,'LONG_TEXT',NULL,TRUE,TRUE UNION ALL
SELECT 'Q-013','MFQ_V1','SEC-005','S4_Q2','List any missing information requests.',2,'LONG_TEXT',NULL,TRUE,TRUE;
