USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

INSERT INTO APP_ROLE (ROLE_ID, ROLE_CODE, ROLE_NAME, IS_ACTIVE)
SELECT 'ROLE-ANALYST','CLAIMS_ANALYST','Claims Analyst',TRUE UNION ALL
SELECT 'ROLE-FACULTY','MEDICAL_FACULTY','Medical Faculty',TRUE UNION ALL
SELECT 'ROLE-ADVICE','ADVICE_TEAM','Advice Team',TRUE UNION ALL
SELECT 'ROLE-EXEC','EXECUTIVE','Executive',TRUE UNION ALL
SELECT 'ROLE-ADMIN','ADMIN','Admin',TRUE;

INSERT INTO APP_PERMISSION (PERMISSION_ID, PERMISSION_CODE, PERMISSION_NAME)
SELECT 'PERM-VIEW','VIEW_CLAIMS','View Claims' UNION ALL
SELECT 'PERM-ASSIGN','ASSIGN_CLAIMS','Assign Claims' UNION ALL
SELECT 'PERM-APPROVE','APPROVE_MFQ','Approve MFQ' UNION ALL
SELECT 'PERM-REPORTS','VIEW_REPORTS','View Reports' UNION ALL
SELECT 'PERM-ADMIN','MANAGE_USERS','Manage Users';

INSERT INTO APP_ROLE_PERMISSION (ROLE_PERMISSION_ID, ROLE_ID, PERMISSION_ID, IS_ACTIVE)
SELECT 'ROP-001','ROLE-ANALYST','PERM-VIEW',TRUE UNION ALL
SELECT 'ROP-002','ROLE-ANALYST','PERM-ASSIGN',TRUE UNION ALL
SELECT 'ROP-003','ROLE-FACULTY','PERM-VIEW',TRUE UNION ALL
SELECT 'ROP-004','ROLE-ADVICE','PERM-VIEW',TRUE UNION ALL
SELECT 'ROP-005','ROLE-EXEC','PERM-REPORTS',TRUE UNION ALL
SELECT 'ROP-006','ROLE-ADMIN','PERM-ADMIN',TRUE;

INSERT INTO APP_USER (USER_ID, USERNAME, EMAIL, DISPLAY_NAME, IS_ACTIVE)
SELECT 'USR-001','claims.analyst','claims.analyst@magmutual.demo','Casey Analyst',TRUE UNION ALL
SELECT 'USR-002','faculty.one','faculty.one@magmutual.demo','Dr. Jordan Faculty',TRUE UNION ALL
SELECT 'USR-003','advice.team','advice.team@magmutual.demo','Taylor Advice',TRUE UNION ALL
SELECT 'USR-004','executive.user','executive.user@magmutual.demo','Morgan Executive',TRUE UNION ALL
SELECT 'USR-005','portal.admin','portal.admin@magmutual.demo','Riley Admin',TRUE;

INSERT INTO APP_USER_ROLE (USER_ROLE_ID, USER_ID, ROLE_ID, IS_ACTIVE)
SELECT 'URO-001','USR-001','ROLE-ANALYST',TRUE UNION ALL
SELECT 'URO-002','USR-002','ROLE-FACULTY',TRUE UNION ALL
SELECT 'URO-003','USR-003','ROLE-ADVICE',TRUE UNION ALL
SELECT 'URO-004','USR-004','ROLE-EXEC',TRUE UNION ALL
SELECT 'URO-005','USR-005','ROLE-ADMIN',TRUE;

INSERT INTO FACULTY_PROFILE (FACULTY_ID, USER_ID, PRIMARY_SPECIALTY, AVAILABILITY_STATUS, QUALITY_SCORE, ON_TIME_RATE)
SELECT 'FAC-001','USR-002','Obstetrics & Gynecology','AVAILABLE',0.94,0.91;

INSERT INTO FACULTY_SPECIALTY (FACULTY_SPECIALTY_ID, FACULTY_ID, SPECIALTY_CODE, SPECIALTY_NAME, IS_PRIMARY)
SELECT 'FSP-001','FAC-001','OBGYN','Obstetrics & Gynecology',TRUE;

INSERT INTO CLAIM (CLAIM_ID, FILE_NUMBER, PATIENT_NAME, CLAIM_STATUS, PRIORITY, DATE_REQUESTED)
SELECT 'CLM-1001','MM-240001','A. Patient','MFQ Generated','High','2026-03-03'::DATE UNION ALL
SELECT 'CLM-1002','MM-240002','B. Patient','Assigned','Medium','2026-03-07'::DATE UNION ALL
SELECT 'CLM-1003','MM-240003','C. Patient','Approved','Low','2026-03-11'::DATE UNION ALL
SELECT 'CLM-1004','MM-240004','D. Patient','Rejected','High','2026-03-18'::DATE;

INSERT INTO CLAIM_DEFENDANT (DEFENDANT_ID, CLAIM_ID, DEFENDANT_NAME, SPECIALTY, BRIEF_SYNOPSIS, ALLEGED_INJURY_TERMS, ALLEGATION_SUMMARY)
SELECT 'DEF-1001','CLM-1001','Dr. Blake','Obstetrics & Gynecology','Labor and delivery review','Brachial plexus injury','Delayed C-section allegation' UNION ALL
SELECT 'DEF-1002','CLM-1002','Dr. Rivera','Emergency Medicine','ER sepsis timeline','Sepsis progression','Delayed diagnosis allegation' UNION ALL
SELECT 'DEF-1003','CLM-1003','Dr. Chen','General Surgery','Post-op infection','Infection and abscess','Inadequate follow-up allegation' UNION ALL
SELECT 'DEF-1004','CLM-1004','Dr. Kim','Neurology','Stroke consult sequence','Ischemic stroke','Delay in consult allegation';

INSERT INTO CLAIM_ASSIGNMENT (ASSIGNMENT_ID, CLAIM_ID, ASSIGNED_TO_USER_ID, ASSIGNED_BY_USER_ID, ASSIGNMENT_STATUS, PRIORITY)
SELECT 'ASG-001','CLM-1002','USR-002','USR-001','ACTIVE','Medium' UNION ALL
SELECT 'ASG-002','CLM-1001','USR-001','USR-005','ACTIVE','High';

INSERT INTO PIPELINE_RUN (RUN_ID, CLAIM_ID, DEFENDANT_ID, STATUS, AI_CONFIDENCE, STARTED_TS, COMPLETED_TS)
SELECT 'RUN-001','CLM-1001','DEF-1001','COMPLETED',0.93,'2026-03-03 10:00:00'::TIMESTAMP_LTZ,'2026-03-03 10:07:00'::TIMESTAMP_LTZ UNION ALL
SELECT 'RUN-002','CLM-1002','DEF-1002','COMPLETED',0.87,'2026-03-07 14:00:00'::TIMESTAMP_LTZ,'2026-03-07 14:12:00'::TIMESTAMP_LTZ;

INSERT INTO CLAIM_SUMMARY (SUMMARY_ID, CLAIM_ID, DEFENDANT_ID, SUMMARY_TYPE, SUMMARY_TEXT)
SELECT 'SUM-001','CLM-1001','DEF-1001','RECORDS_SUMMARY','Records indicate prolonged labor with evolving fetal distress.' UNION ALL
SELECT 'SUM-002','CLM-1001','DEF-1001','MEDCRON','Timeline: admission, labor progression, fetal decelerations, C-section.' UNION ALL
SELECT 'SUM-003','CLM-1001','DEF-1001','LEGAL_MEMO','Potential exposure centers on timing and escalation decisions.';

INSERT INTO MFQ_ANSWER (ANSWER_ID, DEFENDANT_ID, QUESTION_ID, ANSWER_TEXT, CONFIDENCE_SCORE, STATUS, IS_CURRENT)
SELECT 'ANS-001','DEF-1001','Q-005','YES',0.98,'GENERATED',TRUE UNION ALL
SELECT 'ANS-002','DEF-1001','Q-006','Timeline reconstructed from admission and nursing records.',0.90,'GENERATED',TRUE UNION ALL
SELECT 'ANS-003','DEF-1001','Q-007','NO',0.84,'GENERATED',TRUE;

INSERT INTO MFQ_ANSWER (ANSWER_ID, DEFENDANT_ID, QUESTION_ID, ANSWER_TEXT, ANSWER_JSON, CONFIDENCE_SCORE, STATUS, IS_CURRENT)
SELECT 'ANS-004','DEF-1001','Q-008','Deviation details',PARSE_JSON('{"factors":["delay in escalation","late consult"]}'),0.82,'GENERATED',TRUE;

INSERT INTO HUMAN_REVIEW (REVIEW_ID, CLAIM_ID, DEFENDANT_ID, REVIEWER_USER_ID, REVIEW_STATUS, REVIEW_NOTES)
SELECT 'REV-001','CLM-1001','DEF-1001','USR-003','IN_PROGRESS','Awaiting specialty concurrence.';

INSERT INTO CLAIM_DOCUMENT (CLAIM_DOCUMENT_ID, CLAIM_ID, DEFENDANT_ID, FILE_NAME, DOC_TYPE, OCR_STATUS)
SELECT 'DOC-001','CLM-1001','DEF-1001','delivery_note.pdf','MEDICAL_RECORD','COMPLETED' UNION ALL
SELECT 'DOC-002','CLM-1002','DEF-1002','ed_chart.pdf','MEDICAL_RECORD','COMPLETED';

INSERT INTO NOTIFICATION_EVENT (NOTIFICATION_ID, USER_ID, EVENT_TYPE, EVENT_TITLE, EVENT_MESSAGE, CLAIM_ID, EVENT_PRIORITY, IS_READ, PAYLOAD)
SELECT 'NTF-001','USR-001','CLAIM_READY','MFQ Generated','Claim CLM-1001 is ready for analyst review.','CLM-1001','INFO',FALSE,NULL UNION ALL
SELECT 'NTF-002','USR-002','ASSIGNED','New Assignment','Claim CLM-1002 was assigned to you.','CLM-1002','HIGH',FALSE,NULL;

INSERT INTO NOTIFICATION_EVENT (NOTIFICATION_ID, USER_ID, EVENT_TYPE, EVENT_TITLE, EVENT_MESSAGE, CLAIM_ID, EVENT_PRIORITY, IS_READ, PAYLOAD)
SELECT 'NTF-003','USR-005','WORKFLOW','Approval Logged','Claim CLM-1003 moved to Approved.','CLM-1003','INFO',TRUE,
       PARSE_JSON('{"from":"Assigned","to":"Approved"}');

INSERT INTO NOTIFICATION_READ_STATUS (READ_STATUS_ID, NOTIFICATION_ID, USER_ID, READ_AT)
SELECT 'RDS-001','NTF-003','USR-005',CURRENT_TIMESTAMP();

INSERT INTO APP_WORKFLOW_EVENT (WORKFLOW_EVENT_ID, CLAIM_ID, DEFENDANT_ID, EVENT_TYPE, FROM_STATUS, TO_STATUS, EVENT_BY_USER_ID, EVENT_NOTE)
SELECT 'WFE-001','CLM-1003','DEF-1003','STATUS_CHANGE','Assigned','Approved','USR-003','Faculty consensus reached.';

INSERT INTO MISSING_DOCUMENT_REQUEST (REQUEST_ID, CLAIM_ID, DEFENDANT_ID, REQUESTED_BY_USER_ID, REQUEST_STATUS, REQUEST_REASON, REQUESTED_AT)
SELECT 'MDR-001','CLM-1004','DEF-1004','USR-002','OPEN','Need neurology consult notes.','2026-03-19 09:30:00'::TIMESTAMP_LTZ;
