-- 07_validation_queries.sql
-- Quick validation checks after setup and seeding.

SELECT 'claims' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM MFQ_CLAIMS
UNION ALL
SELECT 'answers' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM MFQ_ANSWERS
UNION ALL
SELECT 'notifications' AS OBJECT_NAME, COUNT(*) AS ROW_COUNT FROM MFQ_NOTIFICATIONS
;

SELECT STATUS, COUNT(*) AS CLAIM_COUNT
FROM MFQ_CLAIMS_VW
GROUP BY STATUS
ORDER BY CLAIM_COUNT DESC;

SELECT APP_ROLE, PAGE_KEY, IS_ALLOWED
FROM MFQ_ROLE_PAGE_ACCESS
ORDER BY APP_ROLE, PAGE_KEY;
