-- Validation queries for MFQ UI objects
SELECT COUNT(*) AS CLAIM_COUNT FROM CLAIM;
SELECT STATUS, COUNT(*) AS CLAIMS_BY_STATUS FROM MFQ_CLAIMS_VW GROUP BY STATUS ORDER BY STATUS;
SELECT COUNT(*) AS SECTION_COUNT FROM QST_SECTION WHERE FORM_KEY = 'MFQ_V1';
SELECT COUNT(*) AS QUESTION_COUNT FROM QST_QUESTION WHERE FORM_KEY = 'MFQ_V1' AND IS_CURRENT = TRUE;
SELECT COUNT(*) AS ANSWER_COUNT FROM MFQ_ANSWER WHERE IS_CURRENT = TRUE;
SELECT COUNT(*) AS UI_VIEW_ROWS FROM MFQ_CLAIMS_VW;
SELECT COUNT(*) AS UI_SECTION_ROWS FROM MFQ_SECTIONS_VW;
SELECT COUNT(*) AS UI_QUESTION_ROWS FROM MFQ_QUESTIONS_VW;
