-- Validation queries for MFQ UI objects
SELECT COUNT(*) AS CLAIM_COUNT FROM MFQ_CLAIMS;
SELECT STATUS, COUNT(*) AS CLAIMS_BY_STATUS FROM MFQ_CLAIMS GROUP BY STATUS ORDER BY STATUS;
SELECT COUNT(*) AS SECTION_COUNT FROM MFQ_QUESTIONS;
SELECT COUNT(*) AS ANSWER_COUNT FROM MFQ_ANSWERS;
SELECT COUNT(*) AS UI_VIEW_ROWS FROM MFQ_CLAIMS_VW;
SELECT COUNT(*) AS UI_SECTION_ROWS FROM MFQ_SECTIONS_VW;
