USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

SELECT COUNT(*) FROM CLAIM;
SELECT COUNT(*) FROM CLAIM_DEFENDANT;
SELECT COUNT(*) FROM MFQ_SECTIONS_VW;
SELECT COUNT(*) FROM MFQ_QUESTIONS_VW;
SELECT COUNT(*) FROM MFQ_CLAIMS_VW;
SELECT COUNT(*) FROM MFQ_RECENT_CLAIMS_VW;
SELECT COUNT(*) FROM MFQ_FORM_WORKSPACE_VW;
SELECT * FROM MFQ_DASHBOARD_KPI_VW;
SELECT * FROM MFQ_RECENT_CLAIMS_VW ORDER BY LAST_UPDATED_TS DESC;
SELECT * FROM MFQ_FORM_WORKSPACE_VW ORDER BY CLAIM_ID, SECTION_ORDER, QUESTION_ORDER;
