DELETE FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.PIPELINE_CONFIG')
WHERE CONFIG_KEY IN (
  'SOURCE_DATABASE','SOURCE_SCHEMA','COMBINED_TABLE_INDEX','DOCUMENT_OCR_RESULTS','DOCUMENT_SENTENCES',
  'FORM_KEY','DEFAULT_EMBEDDING_MODEL','PROMPT_RENDER_LIMIT','MAX_RETRIES','RETRY_BASE_SECONDS',
  'CHRONOLOGY_MAX_STEPS','QUESTION_DEFAULT_TOP_K','RETRIEVAL_MIN_QUALITY',
  'FAITHFULNESS_REVIEW_THRESHOLD','HALLUCINATION_RISK_THRESHOLD'
);

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.PIPELINE_CONFIG')
(CONFIG_KEY, CONFIG_VALUE, DATA_TYPE, DESCRIPTION)
SELECT 'SOURCE_DATABASE', $SOURCE_DB, 'STRING', 'Source OCR database' UNION ALL
SELECT 'SOURCE_SCHEMA', $SOURCE_SCHEMA, 'STRING', 'Source OCR schema' UNION ALL
SELECT 'COMBINED_TABLE_INDEX', $SOURCE_COMBINED_TABLE_INDEX, 'STRING', 'Claim-file index table' UNION ALL
SELECT 'DOCUMENT_OCR_RESULTS', $SOURCE_DOCUMENT_OCR_RESULTS, 'STRING', 'OCR status table' UNION ALL
SELECT 'DOCUMENT_SENTENCES', $SOURCE_DOCUMENT_SENTENCES, 'STRING', 'Sentence source table' UNION ALL
SELECT 'FORM_KEY', 'MFQ_V1', 'STRING', 'Default questionnaire form key' UNION ALL
SELECT 'DEFAULT_EMBEDDING_MODEL', 'snowflake-arctic-embed-l-v2.0', 'STRING', 'Default embedding model' UNION ALL
SELECT 'PROMPT_RENDER_LIMIT', '8000', 'INT', 'Max chars stored for rendered prompts' UNION ALL
SELECT 'MAX_RETRIES', '2', 'INT', 'LLM retry count' UNION ALL
SELECT 'RETRY_BASE_SECONDS', '2', 'INT', 'Base seconds for exponential retry' UNION ALL
SELECT 'CHRONOLOGY_MAX_STEPS', '12', 'INT', 'Maximum ReAct chronology steps' UNION ALL
SELECT 'QUESTION_DEFAULT_TOP_K', '8', 'INT', 'Default semantic retrieval top-k' UNION ALL
SELECT 'RETRIEVAL_MIN_QUALITY', '0.60', 'FLOAT', 'CRAG minimum retrieval quality' UNION ALL
SELECT 'FAITHFULNESS_REVIEW_THRESHOLD', '0.65', 'FLOAT', 'Auto-review threshold for evaluator' UNION ALL
SELECT 'HALLUCINATION_RISK_THRESHOLD', '0.40', 'FLOAT', 'Auto-review threshold for hallucination risk';

DELETE FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_CONFIG');

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_CONFIG')
(MODEL_KEY, PROVIDER, ENDPOINT_URL, SECRET_NAME, TEMPERATURE, MAX_TOKENS, ADDITIONAL_PARAMETERS, IS_ACTIVE)
SELECT 'snowflake-arctic-embed-l-v2.0', 'CORTEX', NULL, NULL,
       0.0, 1024, PARSE_JSON('{}'), TRUE;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_CONFIG')
(MODEL_KEY, PROVIDER, ENDPOINT_URL, SECRET_NAME, TEMPERATURE, MAX_TOKENS, ADDITIONAL_PARAMETERS, IS_ACTIVE)
SELECT 'claude-4-sonnet', 'CORTEX', NULL, NULL,
       0.0, 2500, PARSE_JSON('{}'), TRUE;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_CONFIG')
(MODEL_KEY, PROVIDER, ENDPOINT_URL, SECRET_NAME, TEMPERATURE, MAX_TOKENS, ADDITIONAL_PARAMETERS, IS_ACTIVE)
SELECT 'llama3.1-70b', 'CORTEX', NULL, NULL,
       0.0, 2500, PARSE_JSON('{}'), TRUE;

DELETE FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_ROUTING');

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_ROUTING')
(ROUTE_KEY, TASK_TYPE, SECTION_KEY, QUESTION_KEY, GENERATION_MODEL_KEY, EVALUATION_MODEL_KEY, EMBEDDING_MODEL_KEY, PRIORITY, IS_ACTIVE)
SELECT 'DEFAULT_EMBEDDING', 'EMBEDDING', NULL, NULL,
       'claude-4-sonnet', 'llama3.1-70b', 'snowflake-arctic-embed-l-v2.0',
       100, TRUE;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_ROUTING')
(ROUTE_KEY, TASK_TYPE, SECTION_KEY, QUESTION_KEY, GENERATION_MODEL_KEY, EVALUATION_MODEL_KEY, EMBEDDING_MODEL_KEY, PRIORITY, IS_ACTIVE)
SELECT 'DEFAULT_CHRONOLOGY', 'CHRONOLOGY', NULL, NULL,
       'claude-4-sonnet', 'llama3.1-70b', 'snowflake-arctic-embed-l-v2.0',
       100, TRUE;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_ROUTING')
(ROUTE_KEY, TASK_TYPE, SECTION_KEY, QUESTION_KEY, GENERATION_MODEL_KEY, EVALUATION_MODEL_KEY, EMBEDDING_MODEL_KEY, PRIORITY, IS_ACTIVE)
SELECT 'DEFAULT_GAP_ANALYSIS', 'GAP_ANALYSIS', NULL, NULL,
       'claude-4-sonnet', 'llama3.1-70b', 'snowflake-arctic-embed-l-v2.0',
       100, TRUE;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_ROUTING')
(ROUTE_KEY, TASK_TYPE, SECTION_KEY, QUESTION_KEY, GENERATION_MODEL_KEY, EVALUATION_MODEL_KEY, EMBEDDING_MODEL_KEY, PRIORITY, IS_ACTIVE)
SELECT 'DEFAULT_MFQ_ANSWER', 'MFQ_ANSWER', NULL, NULL,
       'claude-4-sonnet', 'llama3.1-70b', 'snowflake-arctic-embed-l-v2.0',
       100, TRUE;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.LLM_ROUTING')
(ROUTE_KEY, TASK_TYPE, SECTION_KEY, QUESTION_KEY, GENERATION_MODEL_KEY, EVALUATION_MODEL_KEY, EMBEDDING_MODEL_KEY, PRIORITY, IS_ACTIVE)
SELECT 'DEFAULT_SUMMARY', 'SUMMARY', NULL, NULL,
       'claude-4-sonnet', 'llama3.1-70b', 'snowflake-arctic-embed-l-v2.0',
       100, TRUE;

DELETE FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.WORKFLOW_STATUS_DEF');

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.WORKFLOW_STATUS_DEF')
(ENTITY_TYPE, STATUS_CODE, ALLOWED_NEXT, DESCRIPTION)
SELECT 'PIPELINE_RUN', 'PENDING', PARSE_JSON('["RUNNING", "FAILED"]'), NULL;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.WORKFLOW_STATUS_DEF')
(ENTITY_TYPE, STATUS_CODE, ALLOWED_NEXT, DESCRIPTION)
SELECT 'PIPELINE_RUN', 'RUNNING', PARSE_JSON('["COMPLETED", "PARTIAL", "FAILED"]'), NULL;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.WORKFLOW_STATUS_DEF')
(ENTITY_TYPE, STATUS_CODE, ALLOWED_NEXT, DESCRIPTION)
SELECT 'PIPELINE_RUN', 'PARTIAL', PARSE_JSON('["RUNNING", "COMPLETED", "FAILED"]'), NULL;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.WORKFLOW_STATUS_DEF')
(ENTITY_TYPE, STATUS_CODE, ALLOWED_NEXT, DESCRIPTION)
SELECT 'PIPELINE_RUN', 'COMPLETED', PARSE_JSON('[]'), NULL;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.WORKFLOW_STATUS_DEF')
(ENTITY_TYPE, STATUS_CODE, ALLOWED_NEXT, DESCRIPTION)
SELECT 'QUESTION', 'PENDING', PARSE_JSON('["GENERATED", "FAILED", "SKIPPED"]'), NULL;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.WORKFLOW_STATUS_DEF')
(ENTITY_TYPE, STATUS_CODE, ALLOWED_NEXT, DESCRIPTION)
SELECT 'QUESTION', 'GENERATED', PARSE_JSON('["EVALUATED", "FAILED", "OVERRIDDEN"]'), NULL;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.WORKFLOW_STATUS_DEF')
(ENTITY_TYPE, STATUS_CODE, ALLOWED_NEXT, DESCRIPTION)
SELECT 'QUESTION', 'EVALUATED', PARSE_JSON('["APPROVED", "REJECTED", "OVERRIDDEN"]'), NULL;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.WORKFLOW_STATUS_DEF')
(ENTITY_TYPE, STATUS_CODE, ALLOWED_NEXT, DESCRIPTION)
SELECT 'REVIEW', 'PENDING', PARSE_JSON('["APPROVED", "REJECTED", "OVERRIDDEN"]'), NULL;

DELETE FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.SUMMARY_CONFIG');

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.SUMMARY_CONFIG')
(SUMMARY_TYPE, DISPLAY_ORDER, SECTION_KEYS, SEARCH_QUERY, WORD_TARGET, INSTRUCTIONS, IS_ACTIVE)
SELECT 'MEDICAL_CARE', 1, PARSE_JSON('["SEC_III_A", "SEC_III_B", "SEC_III_C", "SEC_III_D", "SEC_III_E"]'),
       'medical care treatment defendant', 450, 'Summarize the care delivered, key decisions, treatment path, and major issues.', TRUE;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.SUMMARY_CONFIG')
(SUMMARY_TYPE, DISPLAY_ORDER, SECTION_KEYS, SEARCH_QUERY, WORD_TARGET, INSTRUCTIONS, IS_ACTIVE)
SELECT 'INJURY', 2, PARSE_JSON('["SEC_II"]'),
       'patient injury harm outcome', 250, 'Summarize injury severity, impact, and outcome.', TRUE;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.SUMMARY_CONFIG')
(SUMMARY_TYPE, DISPLAY_ORDER, SECTION_KEYS, SEARCH_QUERY, WORD_TARGET, INSTRUCTIONS, IS_ACTIVE)
SELECT 'CHRONOLOGY_NARRATIVE', 3, PARSE_JSON('[]'),
       'chronology timeline events', 500, 'Turn chronology events into a clean narrative timeline.', TRUE;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.SUMMARY_CONFIG')
(SUMMARY_TYPE, DISPLAY_ORDER, SECTION_KEYS, SEARCH_QUERY, WORD_TARGET, INSTRUCTIONS, IS_ACTIVE)
SELECT 'ALLEGATION_ANALYSIS', 4, PARSE_JSON('["SEC_III_A", "SEC_III_B", "SEC_III_C", "SEC_III_F"]'),
       'allegations deviation malpractice', 350, 'Focus on allegations, deviations, and contributing factors.', TRUE;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.SUMMARY_CONFIG')
(SUMMARY_TYPE, DISPLAY_ORDER, SECTION_KEYS, SEARCH_QUERY, WORD_TARGET, INSTRUCTIONS, IS_ACTIVE)
SELECT 'SOC', 5, PARSE_JSON('["SEC_III_A", "SEC_III_B", "SEC_III_C", "SEC_III_D", "SEC_III_E", "SEC_III_F", "SEC_IV"]'),
       'standard of care deviation', 300, 'Summarize the standard-of-care assessment and rationale.', TRUE;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.SUMMARY_CONFIG')
(SUMMARY_TYPE, DISPLAY_ORDER, SECTION_KEYS, SEARCH_QUERY, WORD_TARGET, INSTRUCTIONS, IS_ACTIVE)
SELECT 'CAUSATION', 6, PARSE_JSON('["SEC_V", "SEC_III_B", "SEC_III_C"]'),
       'causation injury cause contribution', 300, 'Summarize causation, whether care contributed, and why.', TRUE;

INSERT INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.SUMMARY_CONFIG')
(SUMMARY_TYPE, DISPLAY_ORDER, SECTION_KEYS, SEARCH_QUERY, WORD_TARGET, INSTRUCTIONS, IS_ACTIVE)
SELECT 'FULL_CLAIM', 7, PARSE_JSON('["SEC_I", "SEC_II", "SEC_III_A", "SEC_III_B", "SEC_III_C", "SEC_III_D", "SEC_III_E", "SEC_III_F", "SEC_IV", "SEC_V", "SEC_VI"]'),
       'complete claim overview', 700, 'Create an executive claim summary combining chronology, injury, deviations, SOC, and causation.', TRUE;
