USE ROLE ACCOUNTADMIN;
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MAGMUTUAL_MFQ_APP;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE APP_USER (
  USER_ID STRING NOT NULL,
  USERNAME STRING NOT NULL,
  EMAIL STRING,
  DISPLAY_NAME STRING,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (USER_ID)
);

CREATE OR REPLACE TABLE APP_ROLE (
  ROLE_ID STRING NOT NULL,
  ROLE_CODE STRING NOT NULL,
  ROLE_NAME STRING NOT NULL,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (ROLE_ID)
);

CREATE OR REPLACE TABLE APP_USER_ROLE (
  USER_ROLE_ID STRING NOT NULL,
  USER_ID STRING NOT NULL,
  ROLE_ID STRING NOT NULL,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (USER_ROLE_ID)
);

CREATE OR REPLACE TABLE APP_PERMISSION (
  PERMISSION_ID STRING NOT NULL,
  PERMISSION_CODE STRING NOT NULL,
  PERMISSION_NAME STRING NOT NULL,
  PRIMARY KEY (PERMISSION_ID)
);

CREATE OR REPLACE TABLE APP_ROLE_PERMISSION (
  ROLE_PERMISSION_ID STRING NOT NULL,
  ROLE_ID STRING NOT NULL,
  PERMISSION_ID STRING NOT NULL,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  PRIMARY KEY (ROLE_PERMISSION_ID)
);

CREATE OR REPLACE TABLE CLAIM_ASSIGNMENT (
  ASSIGNMENT_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  ASSIGNED_TO_USER_ID STRING NOT NULL,
  ASSIGNED_BY_USER_ID STRING,
  ASSIGNMENT_STATUS STRING,
  PRIORITY STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  LAST_UPDATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (ASSIGNMENT_ID)
);

CREATE OR REPLACE TABLE CLAIM_SECTION_ASSIGNMENT (
  SECTION_ASSIGNMENT_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  SECTION_ID STRING NOT NULL,
  ASSIGNED_TO_USER_ID STRING NOT NULL,
  ASSIGNMENT_STATUS STRING,
  ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (SECTION_ASSIGNMENT_ID)
);

CREATE OR REPLACE TABLE NOTIFICATION_EVENT (
  NOTIFICATION_ID STRING NOT NULL,
  USER_ID STRING NOT NULL,
  EVENT_TYPE STRING,
  EVENT_TITLE STRING,
  EVENT_MESSAGE STRING,
  CLAIM_ID STRING,
  EVENT_PRIORITY STRING,
  EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  IS_READ BOOLEAN DEFAULT FALSE,
  PAYLOAD VARIANT,
  PRIMARY KEY (NOTIFICATION_ID)
);

CREATE OR REPLACE TABLE NOTIFICATION_READ_STATUS (
  READ_STATUS_ID STRING NOT NULL,
  NOTIFICATION_ID STRING NOT NULL,
  USER_ID STRING NOT NULL,
  READ_AT TIMESTAMP_LTZ,
  PRIMARY KEY (READ_STATUS_ID)
);

CREATE OR REPLACE TABLE CLAIM_DOCUMENT (
  CLAIM_DOCUMENT_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING,
  FILE_NAME STRING,
  DOC_TYPE STRING,
  OCR_STATUS STRING,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (CLAIM_DOCUMENT_ID)
);

CREATE OR REPLACE TABLE APP_AUDIT_LOG (
  AUDIT_ID STRING NOT NULL,
  ENTITY_TYPE STRING,
  ENTITY_ID STRING,
  ACTION_TYPE STRING,
  ACTION_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  ACTOR_USER_ID STRING,
  PRIMARY KEY (AUDIT_ID)
);

CREATE OR REPLACE TABLE APP_WORKFLOW_EVENT (
  WORKFLOW_EVENT_ID STRING NOT NULL,
  CLAIM_ID STRING,
  DEFENDANT_ID STRING,
  EVENT_TYPE STRING,
  FROM_STATUS STRING,
  TO_STATUS STRING,
  EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  EVENT_BY_USER_ID STRING,
  EVENT_NOTE STRING,
  PRIMARY KEY (WORKFLOW_EVENT_ID)
);

CREATE OR REPLACE TABLE APPIAN_OUTBOX_EVENT (
  OUTBOX_EVENT_ID STRING NOT NULL,
  ENTITY_TYPE STRING,
  ENTITY_ID STRING,
  EVENT_TYPE STRING,
  EVENT_PAYLOAD VARIANT,
  DELIVERY_STATUS STRING,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  PRIMARY KEY (OUTBOX_EVENT_ID)
);

CREATE OR REPLACE TABLE FACULTY_PROFILE (
  FACULTY_ID STRING NOT NULL,
  USER_ID STRING NOT NULL,
  PRIMARY_SPECIALTY STRING,
  AVAILABILITY_STATUS STRING,
  QUALITY_SCORE FLOAT,
  ON_TIME_RATE FLOAT,
  PRIMARY KEY (FACULTY_ID)
);

CREATE OR REPLACE TABLE FACULTY_SPECIALTY (
  FACULTY_SPECIALTY_ID STRING NOT NULL,
  FACULTY_ID STRING NOT NULL,
  SPECIALTY_CODE STRING,
  SPECIALTY_NAME STRING,
  IS_PRIMARY BOOLEAN,
  PRIMARY KEY (FACULTY_SPECIALTY_ID)
);

CREATE OR REPLACE TABLE MISSING_DOCUMENT_REQUEST (
  REQUEST_ID STRING NOT NULL,
  CLAIM_ID STRING NOT NULL,
  DEFENDANT_ID STRING,
  REQUESTED_BY_USER_ID STRING,
  REQUEST_STATUS STRING,
  REQUEST_REASON STRING,
  REQUESTED_AT TIMESTAMP_LTZ,
  PRIMARY KEY (REQUEST_ID)
);

CREATE OR REPLACE VIEW MFQ_SECTIONS_VW AS
SELECT FORM_KEY, SECTION_ID, SECTION_KEY, SECTION_NAME, SECTION_ORDER, IS_ACTIVE
FROM MFQ_SECTIONS
WHERE IS_ACTIVE = TRUE;

CREATE OR REPLACE VIEW MFQ_QUESTIONS_VW AS
SELECT FORM_KEY, SECTION_ID, QUESTION_ID, QUESTION_KEY, QUESTION_TEXT, QUESTION_ORDER, ANSWER_TYPE, ALLOWED_VALUES, IS_CURRENT, IS_ACTIVE
FROM MFQ_QUESTIONS
WHERE IS_CURRENT = TRUE
  AND IS_ACTIVE = TRUE;

CREATE OR REPLACE VIEW MFQ_CLAIMS_VW AS
SELECT
  c.CLAIM_ID,
  c.FILE_NUMBER,
  c.PATIENT_NAME,
  c.CLAIM_STATUS AS STATUS,
  COALESCE(c.PRIORITY, ca.PRIORITY, 'Medium') AS PRIORITY,
  c.DATE_REQUESTED,
  d.DEFENDANT_ID,
  d.DEFENDANT_NAME,
  d.SPECIALTY,
  au.USERNAME AS ASSIGNED_TO,
  pr.AI_CONFIDENCE,
  c.LAST_UPDATED_TS
FROM CLAIM c
JOIN CLAIM_DEFENDANT d ON c.CLAIM_ID = d.CLAIM_ID
LEFT JOIN CLAIM_ASSIGNMENT ca ON c.CLAIM_ID = ca.CLAIM_ID
LEFT JOIN APP_USER au ON ca.ASSIGNED_TO_USER_ID = au.USER_ID
LEFT JOIN PIPELINE_RUN pr ON pr.CLAIM_ID = c.CLAIM_ID AND pr.DEFENDANT_ID = d.DEFENDANT_ID;

CREATE OR REPLACE VIEW MFQ_RECENT_CLAIMS_VW AS
SELECT *
FROM MFQ_CLAIMS_VW
QUALIFY ROW_NUMBER() OVER (ORDER BY LAST_UPDATED_TS DESC, CLAIM_ID) <= 100;

CREATE OR REPLACE VIEW MFQ_DASHBOARD_KPI_VW AS
SELECT
  COUNT(*) AS TOTAL_ACTIVE_CLAIMS,
  COUNT_IF(STATUS = 'MFQ Generated') AS MFQ_GENERATED,
  COUNT_IF(STATUS = 'Assigned') AS ASSIGNED,
  COUNT_IF(STATUS = 'Approved') AS APPROVED,
  COUNT_IF(STATUS = 'Rejected') AS REJECTED
FROM MFQ_CLAIMS_VW;

CREATE OR REPLACE VIEW MFQ_CLAIM_DETAIL_VW AS
SELECT
  mc.*,
  cs_records.SUMMARY_TEXT AS RECORDS_SUMMARY,
  cs_medcron.SUMMARY_TEXT AS MEDCRON_TEXT,
  cs_legal.SUMMARY_TEXT AS LEGAL_MEMO_TEXT
FROM MFQ_CLAIMS_VW mc
LEFT JOIN CLAIM_SUMMARY cs_records ON cs_records.CLAIM_ID = mc.CLAIM_ID AND cs_records.SUMMARY_TYPE = 'RECORDS_SUMMARY'
LEFT JOIN CLAIM_SUMMARY cs_medcron ON cs_medcron.CLAIM_ID = mc.CLAIM_ID AND cs_medcron.SUMMARY_TYPE = 'MEDCRON'
LEFT JOIN CLAIM_SUMMARY cs_legal ON cs_legal.CLAIM_ID = mc.CLAIM_ID AND cs_legal.SUMMARY_TYPE = 'LEGAL_MEMO';

CREATE OR REPLACE VIEW MFQ_FORM_WORKSPACE_VW AS
SELECT
  mc.CLAIM_ID,
  mc.DEFENDANT_ID,
  s.SECTION_ID,
  s.SECTION_NAME,
  s.SECTION_ORDER,
  q.QUESTION_ID,
  q.QUESTION_KEY,
  q.QUESTION_TEXT,
  q.QUESTION_ORDER,
  q.ANSWER_TYPE,
  q.ALLOWED_VALUES,
  a.ANSWER_ID,
  a.ANSWER_TEXT,
  a.ANSWER_JSON,
  a.CONFIDENCE_SCORE,
  a.STATUS AS ANSWER_STATUS
FROM MFQ_CLAIMS_VW mc
JOIN MFQ_SECTIONS_VW s ON s.FORM_KEY = 'MFQ_V1'
JOIN MFQ_QUESTIONS_VW q ON q.FORM_KEY = s.FORM_KEY AND q.SECTION_ID = s.SECTION_ID
LEFT JOIN MFQ_ANSWER a
  ON a.DEFENDANT_ID = mc.DEFENDANT_ID
 AND a.QUESTION_ID = q.QUESTION_ID
 AND a.IS_CURRENT = TRUE;

CREATE OR REPLACE VIEW MFQ_NOTIFICATION_VW AS
SELECT
  n.NOTIFICATION_ID,
  n.USER_ID,
  u.USERNAME,
  n.EVENT_TYPE,
  n.EVENT_TITLE,
  n.EVENT_MESSAGE,
  n.CLAIM_ID,
  n.EVENT_PRIORITY,
  n.EVENT_TS,
  COALESCE(rs.READ_AT IS NOT NULL, n.IS_READ) AS IS_READ
FROM NOTIFICATION_EVENT n
LEFT JOIN NOTIFICATION_READ_STATUS rs ON rs.NOTIFICATION_ID = n.NOTIFICATION_ID AND rs.USER_ID = n.USER_ID
LEFT JOIN APP_USER u ON u.USER_ID = n.USER_ID;

CREATE OR REPLACE VIEW MFQ_NOTIFICATIONS_VW AS
SELECT * FROM MFQ_NOTIFICATION_VW;

CREATE OR REPLACE VIEW MFQ_ASSIGNMENT_QUEUE_VW AS
SELECT
  ca.ASSIGNMENT_ID,
  ca.CLAIM_ID,
  c.PATIENT_NAME,
  d.DEFENDANT_NAME,
  d.SPECIALTY,
  ca.PRIORITY,
  ca.ASSIGNMENT_STATUS,
  ca.ASSIGNED_AT,
  au.USERNAME AS ASSIGNED_TO,
  assigner.USERNAME AS ASSIGNED_BY
FROM CLAIM_ASSIGNMENT ca
JOIN CLAIM c ON c.CLAIM_ID = ca.CLAIM_ID
JOIN CLAIM_DEFENDANT d ON d.CLAIM_ID = ca.CLAIM_ID
LEFT JOIN APP_USER au ON au.USER_ID = ca.ASSIGNED_TO_USER_ID
LEFT JOIN APP_USER assigner ON assigner.USER_ID = ca.ASSIGNED_BY_USER_ID;

CREATE OR REPLACE VIEW MFQ_REPORT_STATUS_VW AS
SELECT STATUS, COUNT(*) AS CLAIM_COUNT
FROM MFQ_CLAIMS_VW
GROUP BY STATUS;

CREATE OR REPLACE VIEW MFQ_REPORT_FACULTY_PERFORMANCE_VW AS
SELECT
  au.USERNAME AS FACULTY_USERNAME,
  COUNT(*) AS TOTAL_ASSIGNED,
  COUNT_IF(mc.STATUS = 'Approved') AS APPROVED_COUNT,
  AVG(COALESCE(mc.AI_CONFIDENCE, 0)) AS AVG_AI_CONFIDENCE
FROM MFQ_CLAIMS_VW mc
LEFT JOIN APP_USER au ON au.USERNAME = mc.ASSIGNED_TO
GROUP BY au.USERNAME;

CREATE OR REPLACE VIEW MFQ_REPORT_SPECIALTY_DISTRIBUTION_VW AS
SELECT SPECIALTY, COUNT(*) AS CLAIM_COUNT
FROM MFQ_CLAIMS_VW
GROUP BY SPECIALTY;
