-- 04_create_ui_objects.sql
-- UI/RBAC/workflow extension objects for MFQ Portal.
-- NOTE: This script intentionally reuses existing core objects (CLAIM, CLAIM_DEFENDANT,
-- QST_QUESTION, MFQ_ANSWER, HUMAN_REVIEW) and does not recreate them.

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_USER') (
    USER_ID STRING NOT NULL,
    USERNAME STRING NOT NULL,
    EMAIL STRING,
    DISPLAY_NAME STRING,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    LAST_LOGIN_AT TIMESTAMP_LTZ,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USER_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_ROLE') (
    ROLE_ID STRING NOT NULL,
    ROLE_CODE STRING NOT NULL,
    ROLE_NAME STRING NOT NULL,
    DESCRIPTION STRING,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ROLE_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_USER_ROLE') (
    USER_ROLE_ID STRING NOT NULL,
    USER_ID STRING NOT NULL,
    ROLE_ID STRING NOT NULL,
    EFFECTIVE_FROM TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    EFFECTIVE_TO TIMESTAMP_LTZ,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (USER_ROLE_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_PERMISSION') (
    PERMISSION_ID STRING NOT NULL,
    PERMISSION_CODE STRING NOT NULL,
    PERMISSION_NAME STRING NOT NULL,
    DESCRIPTION STRING,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PERMISSION_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_ROLE_PERMISSION') (
    ROLE_PERMISSION_ID STRING NOT NULL,
    ROLE_ID STRING NOT NULL,
    PERMISSION_ID STRING NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ROLE_PERMISSION_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_ASSIGNMENT') (
    ASSIGNMENT_ID STRING NOT NULL,
    CLAIM_ID STRING NOT NULL,
    ASSIGNED_TO_USER_ID STRING NOT NULL,
    ASSIGNED_BY_USER_ID STRING,
    ASSIGNMENT_ROLE_CODE STRING,
    ASSIGNMENT_STATUS STRING DEFAULT 'ACTIVE',
    PRIORITY STRING DEFAULT 'Medium',
    DUE_AT TIMESTAMP_LTZ,
    ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UNASSIGNED_AT TIMESTAMP_LTZ,
    NOTES STRING,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ASSIGNMENT_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_SECTION_ASSIGNMENT') (
    SECTION_ASSIGNMENT_ID STRING NOT NULL,
    CLAIM_ID STRING NOT NULL,
    SECTION_ID STRING NOT NULL,
    ASSIGNED_TO_USER_ID STRING NOT NULL,
    ASSIGNED_BY_USER_ID STRING,
    ASSIGNMENT_STATUS STRING DEFAULT 'ACTIVE',
    ASSIGNED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    COMPLETED_AT TIMESTAMP_LTZ,
    NOTES STRING,
    PRIMARY KEY (SECTION_ASSIGNMENT_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.NOTIFICATION_EVENT') (
    NOTIFICATION_ID STRING NOT NULL,
    USER_ID STRING NOT NULL,
    EVENT_TYPE STRING NOT NULL,
    EVENT_TITLE STRING NOT NULL,
    EVENT_MESSAGE STRING,
    CLAIM_ID STRING,
    EVENT_PRIORITY STRING DEFAULT 'INFO',
    IS_READ BOOLEAN DEFAULT FALSE,
    ACTION_URL STRING,
    EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT TIMESTAMP_LTZ,
    PAYLOAD VARIANT,
    PRIMARY KEY (NOTIFICATION_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.NOTIFICATION_READ_STATUS') (
    READ_STATUS_ID STRING NOT NULL,
    NOTIFICATION_ID STRING NOT NULL,
    USER_ID STRING NOT NULL,
    READ_AT TIMESTAMP_LTZ,
    DISMISSED_AT TIMESTAMP_LTZ,
    PRIMARY KEY (READ_STATUS_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_DOCUMENT') (
    CLAIM_DOCUMENT_ID STRING NOT NULL,
    CLAIM_ID STRING NOT NULL,
    DEFENDANT_ID STRING,
    FILE_NAME STRING NOT NULL,
    DOC_TYPE STRING,
    DOC_SUBTYPE STRING,
    STORAGE_PATH STRING,
    SOURCE_SYSTEM STRING,
    DOCUMENT_DATE DATE,
    FILE_SIZE_BYTES NUMBER,
    MIME_TYPE STRING,
    OCR_STATUS STRING DEFAULT 'PENDING',
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (CLAIM_DOCUMENT_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_AUDIT_LOG') (
    AUDIT_ID STRING NOT NULL,
    ENTITY_TYPE STRING NOT NULL,
    ENTITY_ID STRING NOT NULL,
    ACTION_TYPE STRING NOT NULL,
    ACTION_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    ACTOR_USER_ID STRING,
    BEFORE_STATE VARIANT,
    AFTER_STATE VARIANT,
    REQUEST_ID STRING,
    SOURCE_CHANNEL STRING,
    PRIMARY KEY (AUDIT_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_WORKFLOW_EVENT') (
    WORKFLOW_EVENT_ID STRING NOT NULL,
    CLAIM_ID STRING,
    DEFENDANT_ID STRING,
    EVENT_TYPE STRING NOT NULL,
    FROM_STATUS STRING,
    TO_STATUS STRING,
    EVENT_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    EVENT_BY_USER_ID STRING,
    EVENT_NOTE STRING,
    EVENT_METADATA VARIANT,
    PRIMARY KEY (WORKFLOW_EVENT_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APPIAN_OUTBOX_EVENT') (
    OUTBOX_EVENT_ID STRING NOT NULL,
    ENTITY_TYPE STRING NOT NULL,
    ENTITY_ID STRING NOT NULL,
    EVENT_TYPE STRING NOT NULL,
    EVENT_PAYLOAD VARIANT NOT NULL,
    DELIVERY_STATUS STRING DEFAULT 'PENDING',
    RETRY_COUNT NUMBER DEFAULT 0,
    LAST_ATTEMPT_AT TIMESTAMP_LTZ,
    DELIVERED_AT TIMESTAMP_LTZ,
    ERROR_MESSAGE STRING,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (OUTBOX_EVENT_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.FACULTY_PROFILE') (
    FACULTY_ID STRING NOT NULL,
    USER_ID STRING NOT NULL,
    NPI_NUMBER STRING,
    LICENSE_NUMBER STRING,
    PRIMARY_SPECIALTY STRING,
    YEARS_EXPERIENCE NUMBER,
    BOARD_CERTIFICATIONS VARIANT,
    HOME_STATE STRING,
    AVAILABILITY_STATUS STRING DEFAULT 'AVAILABLE',
    MAX_CONCURRENT_ASSIGNMENTS NUMBER DEFAULT 8,
    CURRENT_ASSIGNMENT_COUNT NUMBER DEFAULT 0,
    QUALITY_SCORE FLOAT,
    ON_TIME_RATE FLOAT,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (FACULTY_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.FACULTY_SPECIALTY') (
    FACULTY_SPECIALTY_ID STRING NOT NULL,
    FACULTY_ID STRING NOT NULL,
    SPECIALTY_CODE STRING NOT NULL,
    SPECIALTY_NAME STRING NOT NULL,
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (FACULTY_SPECIALTY_ID)
);

CREATE OR REPLACE TABLE IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MISSING_DOCUMENT_REQUEST') (
    REQUEST_ID STRING NOT NULL,
    CLAIM_ID STRING NOT NULL,
    DEFENDANT_ID STRING,
    REQUESTED_BY_USER_ID STRING,
    REQUEST_TYPE STRING DEFAULT 'MISSING_DOCUMENT',
    REQUEST_STATUS STRING DEFAULT 'OPEN',
    REQUEST_REASON STRING,
    REQUESTED_DOC_TYPE STRING,
    REQUESTED_DOC_DATE_RANGE STRING,
    REQUESTED_AT TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
    RESOLVED_AT TIMESTAMP_LTZ,
    RESOLUTION_NOTE STRING,
    PRIMARY KEY (REQUEST_ID)
);

-- -------------------------
-- UI-facing views
-- -------------------------

CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_CLAIMS_VW') AS
WITH latest_assignment AS (
    SELECT
        ca.CLAIM_ID,
        ca.ASSIGNED_TO_USER_ID,
        ca.ASSIGNMENT_STATUS,
        ca.PRIORITY,
        ca.DUE_AT,
        ca.ASSIGNED_AT,
        ROW_NUMBER() OVER (PARTITION BY ca.CLAIM_ID ORDER BY ca.ASSIGNED_AT DESC) AS rn
    FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_ASSIGNMENT') ca
),
latest_workflow AS (
    SELECT
        w.CLAIM_ID,
        w.TO_STATUS,
        w.EVENT_TS,
        w.EVENT_BY_USER_ID,
        ROW_NUMBER() OVER (PARTITION BY w.CLAIM_ID ORDER BY w.EVENT_TS DESC) AS rn
    FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_WORKFLOW_EVENT') w
)
SELECT
    c.CLAIM_ID,
    c.FILE_NUMBER,
    c.PATIENT_NAME,
    d.DEFENDANT_ID,
    d.DEFENDANT_NAME,
    d.DEFENDANT_SPECIALTY AS SPECIALTY,
    COALESCE(lw.TO_STATUS, 'MFQ Generated') AS STATUS,
    au.USERNAME AS ASSIGNED_TO,
    approver.USERNAME AS APPROVED_BY,
    la.PRIORITY,
    c.CREATED_AT AS DATE_REQUESTED,
    la.DUE_AT,
    c.UPDATED_AT AS LAST_UPDATED_TS,
    EXISTS (
      SELECT 1
      FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_ANSWER') ans
      WHERE ans.DEFENDANT_ID = d.DEFENDANT_ID
        AND ans.IS_CURRENT = TRUE
    ) AS HAS_NEW_MFQ_VERSION
FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM') c
JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_DEFENDANT') d
  ON c.CLAIM_ID = d.CLAIM_ID
LEFT JOIN latest_assignment la
  ON c.CLAIM_ID = la.CLAIM_ID
 AND la.rn = 1
LEFT JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_USER') au
  ON la.ASSIGNED_TO_USER_ID = au.USER_ID
LEFT JOIN latest_workflow lw
  ON c.CLAIM_ID = lw.CLAIM_ID
 AND lw.rn = 1
LEFT JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_USER') approver
  ON lw.EVENT_BY_USER_ID = approver.USER_ID
 AND lw.TO_STATUS = 'Approved';

CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_DASHBOARD_KPI_VW') AS
SELECT
    COUNT(*) AS TOTAL_CLAIMS,
    COUNT_IF(mc.STATUS = 'MFQ Generated') AS MFQ_GENERATED_COUNT,
    COUNT_IF(mc.STATUS = 'Assigned') AS ASSIGNED_COUNT,
    COUNT_IF(mc.STATUS = 'Approved') AS APPROVED_COUNT,
    COUNT_IF(mc.STATUS = 'Rejected') AS REJECTED_COUNT,
    COUNT_IF(mc.STATUS NOT IN ('Approved', 'Rejected')) AS OPEN_CLAIMS_COUNT,
    ROUND(AVG(DATEDIFF('hour', mc.DATE_REQUESTED, COALESCE(mc.LAST_UPDATED_TS, CURRENT_TIMESTAMP()))), 2) AS AVG_AGE_HOURS
FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_CLAIMS_VW') mc;

CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_RECENT_CLAIMS_VW') AS
SELECT *
FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_CLAIMS_VW')
QUALIFY ROW_NUMBER() OVER (ORDER BY LAST_UPDATED_TS DESC, CLAIM_ID) <= 25;

CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_CLAIM_DETAIL_VW') AS
SELECT
    mc.CLAIM_ID,
    mc.FILE_NUMBER,
    mc.PATIENT_NAME,
    mc.DEFENDANT_ID,
    mc.DEFENDANT_NAME,
    mc.SPECIALTY,
    mc.STATUS,
    mc.ASSIGNED_TO,
    mc.PRIORITY,
    mc.DATE_REQUESTED,
    mc.DUE_AT,
    cd.CLAIM_DOCUMENT_ID,
    cd.FILE_NAME,
    cd.DOC_TYPE,
    cd.DOCUMENT_DATE,
    hr.REVIEW_ID,
    hr.REVIEW_STATUS,
    hr.REVIEW_REASON,
    hr.REVIEWER_ID,
    md.REQUEST_ID AS MISSING_REQUEST_ID,
    md.REQUEST_STATUS AS MISSING_REQUEST_STATUS,
    md.REQUESTED_DOC_TYPE
FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_CLAIMS_VW') mc
LEFT JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_DOCUMENT') cd
  ON mc.CLAIM_ID = cd.CLAIM_ID
LEFT JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.HUMAN_REVIEW') hr
  ON mc.DEFENDANT_ID = hr.ENTITY_ID
 AND hr.ENTITY_TYPE = 'DEFENDANT'
LEFT JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MISSING_DOCUMENT_REQUEST') md
  ON mc.CLAIM_ID = md.CLAIM_ID;

CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_ASSIGNMENT_QUEUE_VW') AS
SELECT
    ca.ASSIGNMENT_ID,
    ca.CLAIM_ID,
    c.FILE_NUMBER,
    c.PATIENT_NAME,
    d.DEFENDANT_NAME,
    d.DEFENDANT_SPECIALTY,
    au.USERNAME AS ASSIGNED_TO,
    assigner.USERNAME AS ASSIGNED_BY,
    ca.ASSIGNMENT_ROLE_CODE,
    ca.ASSIGNMENT_STATUS,
    ca.PRIORITY,
    ca.DUE_AT,
    ca.ASSIGNED_AT,
    DATEDIFF('hour', ca.ASSIGNED_AT, CURRENT_TIMESTAMP()) AS AGE_HOURS
FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_ASSIGNMENT') ca
JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM') c
  ON ca.CLAIM_ID = c.CLAIM_ID
JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_DEFENDANT') d
  ON ca.CLAIM_ID = d.CLAIM_ID
LEFT JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_USER') au
  ON ca.ASSIGNED_TO_USER_ID = au.USER_ID
LEFT JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_USER') assigner
  ON ca.ASSIGNED_BY_USER_ID = assigner.USER_ID
WHERE ca.ASSIGNMENT_STATUS = 'ACTIVE';

CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_NOTIFICATION_VW') AS
SELECT
    n.NOTIFICATION_ID,
    n.USER_ID,
    u.USERNAME,
    n.EVENT_TYPE,
    n.EVENT_TITLE,
    n.EVENT_MESSAGE,
    n.CLAIM_ID,
    n.EVENT_PRIORITY,
    COALESCE(rs.READ_AT IS NOT NULL, FALSE) AS IS_READ,
    rs.READ_AT,
    n.EVENT_TS,
    n.ACTION_URL
FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.NOTIFICATION_EVENT') n
LEFT JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.NOTIFICATION_READ_STATUS') rs
  ON n.NOTIFICATION_ID = rs.NOTIFICATION_ID
 AND n.USER_ID = rs.USER_ID
LEFT JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_USER') u
  ON n.USER_ID = u.USER_ID;

CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_REPORT_STATUS_VW') AS
SELECT
    STATUS,
    COUNT(*) AS CLAIM_COUNT,
    ROUND(AVG(DATEDIFF('day', DATE_REQUESTED, COALESCE(LAST_UPDATED_TS, CURRENT_TIMESTAMP()))), 2) AS AVG_AGE_DAYS
FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_CLAIMS_VW')
GROUP BY STATUS;

CREATE OR REPLACE VIEW IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_REPORT_FACULTY_PERFORMANCE_VW') AS
SELECT
    fp.FACULTY_ID,
    u.USERNAME AS FACULTY_USERNAME,
    u.DISPLAY_NAME AS FACULTY_NAME,
    fp.PRIMARY_SPECIALTY,
    fp.AVAILABILITY_STATUS,
    COUNT(DISTINCT ca.CLAIM_ID) AS TOTAL_ASSIGNED_CLAIMS,
    COUNT_IF(mc.STATUS = 'Approved') AS APPROVED_CLAIMS,
    COUNT_IF(mc.STATUS = 'Rejected') AS REJECTED_CLAIMS,
    ROUND(
      IFF(COUNT(DISTINCT ca.CLAIM_ID)=0, 0, COUNT_IF(mc.STATUS = 'Approved') / COUNT(DISTINCT ca.CLAIM_ID) * 100),
      2
    ) AS APPROVAL_RATE_PCT,
    ROUND(AVG(DATEDIFF('hour', ca.ASSIGNED_AT, COALESCE(mc.LAST_UPDATED_TS, CURRENT_TIMESTAMP()))), 2) AS AVG_TAT_HOURS
FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.FACULTY_PROFILE') fp
JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_USER') u
  ON fp.USER_ID = u.USER_ID
LEFT JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_ASSIGNMENT') ca
  ON ca.ASSIGNED_TO_USER_ID = fp.USER_ID
LEFT JOIN IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_CLAIMS_VW') mc
  ON ca.CLAIM_ID = mc.CLAIM_ID
GROUP BY
    fp.FACULTY_ID,
    u.USERNAME,
    u.DISPLAY_NAME,
    fp.PRIMARY_SPECIALTY,
    fp.AVAILABILITY_STATUS;
