-- 04_create_ui_objects.sql
-- UI-serving tables/views for Streamlit in Snowflake app.

CREATE OR REPLACE TABLE MFQ_APP_USERS (
  USERNAME STRING,
  APP_ROLE STRING,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE MFQ_ROLE_PAGE_ACCESS (
  APP_ROLE STRING,
  PAGE_KEY STRING,
  IS_ALLOWED BOOLEAN DEFAULT TRUE
);

CREATE OR REPLACE TABLE MFQ_ASSIGNMENT_RULES (
  RULE_ID STRING,
  SPECIALTY STRING,
  DEFAULT_FACULTY STRING,
  IS_ACTIVE BOOLEAN DEFAULT TRUE,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE MFQ_NOTIFICATIONS (
  NOTIFICATION_ID STRING,
  TARGET_USER STRING,
  TITLE STRING,
  MESSAGE STRING,
  SEVERITY STRING,
  IS_READ BOOLEAN DEFAULT FALSE,
  CREATED_TS TIMESTAMP_LTZ DEFAULT CURRENT_TIMESTAMP(),
  READ_TS TIMESTAMP_LTZ
);

CREATE OR REPLACE VIEW MFQ_NOTIFICATIONS_VW AS
SELECT *
FROM MFQ_NOTIFICATIONS
WHERE CREATED_TS >= DATEADD('day', -90, CURRENT_TIMESTAMP());

-- UI view expected by the app; replace upstream source tables as needed.
CREATE OR REPLACE VIEW MFQ_CLAIMS_VW AS
SELECT
  c.CLAIM_ID,
  c.FILE_NUMBER,
  c.PATIENT_NAME,
  d.DEFENDANT_NAME,
  COALESCE(c.STATUS, 'MFQ Generated') AS STATUS,
  'Medium' AS PRIORITY,
  CURRENT_DATE() AS DATE_REQUESTED,
  NULL::STRING AS ASSIGNED_TO,
  d.DEFENDANT_SPECIALTY AS SPECIALTY,
  NULL::STRING AS RECORDS_SUMMARY,
  NULL::STRING AS MEDCRON_TEXT,
  NULL::STRING AS LEGAL_MEMO_TEXT
FROM CLAIM c
LEFT JOIN CLAIM_DEFENDANT d
  ON c.CLAIM_ID = d.CLAIM_ID;

CREATE OR REPLACE VIEW MFQ_SECTIONS_VW AS
SELECT
  a.CLAIM_ID,
  s.SECTION_NAME,
  s.DISPLAY_ORDER AS SECTION_ORDER,
  q.DISPLAY_ORDER AS QUESTION_ORDER,
  q.QUESTION_TEXT,
  a.ANSWER_TEXT,
  a.CONFIDENCE_SCORE,
  a.ANSWER_ID
FROM MFQ_ANSWER a
JOIN QST_QUESTION q ON q.QUESTION_ID = a.QUESTION_ID
JOIN QST_SECTION s ON s.SECTION_ID = q.SECTION_ID
QUALIFY ROW_NUMBER() OVER (PARTITION BY a.ANSWER_ID ORDER BY a.UPDATED_AT DESC) = 1;
