-- 06_seed_demo_data.sql
-- Seeds demo data for MFQ portal UI objects and related core tables.

-- -------------------------
-- Roles, users, permissions
-- -------------------------

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_ROLE') t
USING (
    SELECT * FROM VALUES
      ('ROLE_ANALYST', 'CLAIMS_ANALYST', 'Claims Analyst', 'Performs intake and triage of claims', TRUE),
      ('ROLE_FACULTY', 'MEDICAL_FACULTY', 'Medical Faculty', 'Reviews claims and submits MFQ assessments', TRUE),
      ('ROLE_ADVICE', 'ADVICE_TEAM', 'Advice Team', 'Supports guidance and quality review', TRUE),
      ('ROLE_EXEC', 'EXECUTIVE', 'Executive', 'Executive reporting and oversight', TRUE),
      ('ROLE_ADMIN', 'ADMIN', 'Admin', 'System administrator', TRUE)
) s (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, IS_ACTIVE)
ON t.ROLE_ID = s.ROLE_ID
WHEN MATCHED THEN UPDATE SET
    ROLE_CODE = s.ROLE_CODE,
    ROLE_NAME = s.ROLE_NAME,
    DESCRIPTION = s.DESCRIPTION,
    IS_ACTIVE = s.IS_ACTIVE,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
  INSERT (ROLE_ID, ROLE_CODE, ROLE_NAME, DESCRIPTION, IS_ACTIVE, CREATED_AT, UPDATED_AT)
  VALUES (s.ROLE_ID, s.ROLE_CODE, s.ROLE_NAME, s.DESCRIPTION, s.IS_ACTIVE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_PERMISSION') t
USING (
    SELECT * FROM VALUES
      ('PERM_VIEW_CLAIMS', 'VIEW_CLAIMS', 'View Claims', 'Can view claims list and details'),
      ('PERM_ASSIGN_CLAIMS', 'ASSIGN_CLAIMS', 'Assign Claims', 'Can assign claims to faculty'),
      ('PERM_REVIEW_MFQ', 'REVIEW_MFQ', 'Review MFQ', 'Can review and approve/reject MFQ output'),
      ('PERM_VIEW_REPORTS', 'VIEW_REPORTS', 'View Reports', 'Can access operational and executive reports'),
      ('PERM_MANAGE_USERS', 'MANAGE_USERS', 'Manage Users', 'Can manage users and role access')
) s (PERMISSION_ID, PERMISSION_CODE, PERMISSION_NAME, DESCRIPTION)
ON t.PERMISSION_ID = s.PERMISSION_ID
WHEN MATCHED THEN UPDATE SET
    PERMISSION_CODE = s.PERMISSION_CODE,
    PERMISSION_NAME = s.PERMISSION_NAME,
    DESCRIPTION = s.DESCRIPTION
WHEN NOT MATCHED THEN
  INSERT (PERMISSION_ID, PERMISSION_CODE, PERMISSION_NAME, DESCRIPTION, CREATED_AT)
  VALUES (s.PERMISSION_ID, s.PERMISSION_CODE, s.PERMISSION_NAME, s.DESCRIPTION, CURRENT_TIMESTAMP());

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_USER') t
USING (
    SELECT * FROM VALUES
      ('USR_ANALYST_1', 'claims.analyst', 'claims.analyst@demo.local', 'Casey Analyst', TRUE),
      ('USR_FACULTY_1', 'faculty.one', 'faculty.one@demo.local', 'Dr. Jordan Faculty', TRUE),
      ('USR_FACULTY_2', 'faculty.two', 'faculty.two@demo.local', 'Dr. Avery Faculty', TRUE),
      ('USR_ADVICE_1', 'advice.team', 'advice.team@demo.local', 'Taylor Advice', TRUE),
      ('USR_EXEC_1', 'executive.user', 'executive.user@demo.local', 'Morgan Executive', TRUE),
      ('USR_ADMIN_1', 'portal.admin', 'portal.admin@demo.local', 'Riley Admin', TRUE)
) s (USER_ID, USERNAME, EMAIL, DISPLAY_NAME, IS_ACTIVE)
ON t.USER_ID = s.USER_ID
WHEN MATCHED THEN UPDATE SET
    USERNAME = s.USERNAME,
    EMAIL = s.EMAIL,
    DISPLAY_NAME = s.DISPLAY_NAME,
    IS_ACTIVE = s.IS_ACTIVE,
    UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
  INSERT (USER_ID, USERNAME, EMAIL, DISPLAY_NAME, IS_ACTIVE, CREATED_AT, UPDATED_AT)
  VALUES (s.USER_ID, s.USERNAME, s.EMAIL, s.DISPLAY_NAME, s.IS_ACTIVE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_USER_ROLE') t
USING (
    SELECT * FROM VALUES
      ('UR_ANALYST_1', 'USR_ANALYST_1', 'ROLE_ANALYST', TRUE),
      ('UR_FACULTY_1', 'USR_FACULTY_1', 'ROLE_FACULTY', TRUE),
      ('UR_FACULTY_2', 'USR_FACULTY_2', 'ROLE_FACULTY', TRUE),
      ('UR_ADVICE_1', 'USR_ADVICE_1', 'ROLE_ADVICE', TRUE),
      ('UR_EXEC_1', 'USR_EXEC_1', 'ROLE_EXEC', TRUE),
      ('UR_ADMIN_1', 'USR_ADMIN_1', 'ROLE_ADMIN', TRUE)
) s (USER_ROLE_ID, USER_ID, ROLE_ID, IS_ACTIVE)
ON t.USER_ROLE_ID = s.USER_ROLE_ID
WHEN MATCHED THEN UPDATE SET
    USER_ID = s.USER_ID,
    ROLE_ID = s.ROLE_ID,
    IS_ACTIVE = s.IS_ACTIVE
WHEN NOT MATCHED THEN
  INSERT (USER_ROLE_ID, USER_ID, ROLE_ID, IS_ACTIVE, CREATED_AT)
  VALUES (s.USER_ROLE_ID, s.USER_ID, s.ROLE_ID, s.IS_ACTIVE, CURRENT_TIMESTAMP());

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_ROLE_PERMISSION') t
USING (
    SELECT * FROM VALUES
      ('RP_ANALYST_VIEW', 'ROLE_ANALYST', 'PERM_VIEW_CLAIMS', TRUE),
      ('RP_ANALYST_ASSIGN', 'ROLE_ANALYST', 'PERM_ASSIGN_CLAIMS', TRUE),
      ('RP_FACULTY_VIEW', 'ROLE_FACULTY', 'PERM_VIEW_CLAIMS', TRUE),
      ('RP_FACULTY_REVIEW', 'ROLE_FACULTY', 'PERM_REVIEW_MFQ', TRUE),
      ('RP_ADVICE_VIEW', 'ROLE_ADVICE', 'PERM_VIEW_CLAIMS', TRUE),
      ('RP_ADVICE_REPORTS', 'ROLE_ADVICE', 'PERM_VIEW_REPORTS', TRUE),
      ('RP_EXEC_REPORTS', 'ROLE_EXEC', 'PERM_VIEW_REPORTS', TRUE),
      ('RP_ADMIN_USERS', 'ROLE_ADMIN', 'PERM_MANAGE_USERS', TRUE),
      ('RP_ADMIN_VIEW', 'ROLE_ADMIN', 'PERM_VIEW_CLAIMS', TRUE)
) s (ROLE_PERMISSION_ID, ROLE_ID, PERMISSION_ID, IS_ACTIVE)
ON t.ROLE_PERMISSION_ID = s.ROLE_PERMISSION_ID
WHEN MATCHED THEN UPDATE SET
    ROLE_ID = s.ROLE_ID,
    PERMISSION_ID = s.PERMISSION_ID,
    IS_ACTIVE = s.IS_ACTIVE
WHEN NOT MATCHED THEN
  INSERT (ROLE_PERMISSION_ID, ROLE_ID, PERMISSION_ID, IS_ACTIVE, CREATED_AT)
  VALUES (s.ROLE_PERMISSION_ID, s.ROLE_ID, s.PERMISSION_ID, s.IS_ACTIVE, CURRENT_TIMESTAMP());

-- -------------------------
-- Faculty
-- -------------------------
MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.FACULTY_PROFILE') t
USING (
    SELECT * FROM VALUES
      ('FAC_1', 'USR_FACULTY_1', '1771990001', 'LIC-GA-11001', 'Obstetrics & Gynecology', 16, PARSE_JSON('["ABOG"]'), 'GA', 'AVAILABLE', 10, 2, 0.94, 0.91),
      ('FAC_2', 'USR_FACULTY_2', '1771990002', 'LIC-FL-22002', 'Emergency Medicine', 12, PARSE_JSON('["ABEM"]'), 'FL', 'AVAILABLE', 8, 1, 0.92, 0.88)
) s (FACULTY_ID, USER_ID, NPI_NUMBER, LICENSE_NUMBER, PRIMARY_SPECIALTY, YEARS_EXPERIENCE, BOARD_CERTIFICATIONS, HOME_STATE, AVAILABILITY_STATUS, MAX_CONCURRENT_ASSIGNMENTS, CURRENT_ASSIGNMENT_COUNT, QUALITY_SCORE, ON_TIME_RATE)
ON t.FACULTY_ID = s.FACULTY_ID
WHEN MATCHED THEN UPDATE SET
  USER_ID = s.USER_ID,
  PRIMARY_SPECIALTY = s.PRIMARY_SPECIALTY,
  YEARS_EXPERIENCE = s.YEARS_EXPERIENCE,
  BOARD_CERTIFICATIONS = s.BOARD_CERTIFICATIONS,
  AVAILABILITY_STATUS = s.AVAILABILITY_STATUS,
  CURRENT_ASSIGNMENT_COUNT = s.CURRENT_ASSIGNMENT_COUNT,
  QUALITY_SCORE = s.QUALITY_SCORE,
  ON_TIME_RATE = s.ON_TIME_RATE,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
  INSERT (FACULTY_ID, USER_ID, NPI_NUMBER, LICENSE_NUMBER, PRIMARY_SPECIALTY, YEARS_EXPERIENCE, BOARD_CERTIFICATIONS, HOME_STATE, AVAILABILITY_STATUS, MAX_CONCURRENT_ASSIGNMENTS, CURRENT_ASSIGNMENT_COUNT, QUALITY_SCORE, ON_TIME_RATE, CREATED_AT, UPDATED_AT)
  VALUES (s.FACULTY_ID, s.USER_ID, s.NPI_NUMBER, s.LICENSE_NUMBER, s.PRIMARY_SPECIALTY, s.YEARS_EXPERIENCE, s.BOARD_CERTIFICATIONS, s.HOME_STATE, s.AVAILABILITY_STATUS, s.MAX_CONCURRENT_ASSIGNMENTS, s.CURRENT_ASSIGNMENT_COUNT, s.QUALITY_SCORE, s.ON_TIME_RATE, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.FACULTY_SPECIALTY') t
USING (
    SELECT * FROM VALUES
      ('FSP_1', 'FAC_1', 'OBGYN', 'Obstetrics & Gynecology', TRUE),
      ('FSP_2', 'FAC_1', 'MATERNAL_FETAL', 'Maternal-Fetal Medicine', FALSE),
      ('FSP_3', 'FAC_2', 'EM', 'Emergency Medicine', TRUE)
) s (FACULTY_SPECIALTY_ID, FACULTY_ID, SPECIALTY_CODE, SPECIALTY_NAME, IS_PRIMARY)
ON t.FACULTY_SPECIALTY_ID = s.FACULTY_SPECIALTY_ID
WHEN MATCHED THEN UPDATE SET
  FACULTY_ID = s.FACULTY_ID,
  SPECIALTY_CODE = s.SPECIALTY_CODE,
  SPECIALTY_NAME = s.SPECIALTY_NAME,
  IS_PRIMARY = s.IS_PRIMARY
WHEN NOT MATCHED THEN
  INSERT (FACULTY_SPECIALTY_ID, FACULTY_ID, SPECIALTY_CODE, SPECIALTY_NAME, IS_PRIMARY, CREATED_AT)
  VALUES (s.FACULTY_SPECIALTY_ID, s.FACULTY_ID, s.SPECIALTY_CODE, s.SPECIALTY_NAME, s.IS_PRIMARY, CURRENT_TIMESTAMP());

-- -------------------------
-- Sample claims and defendants (existing core tables)
-- -------------------------
MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM') t
USING (
    SELECT * FROM VALUES
      ('CLM_DEMO_1001', 'MM-2026-1001', 'Jane Doe', 'ACTIVE'),
      ('CLM_DEMO_1002', 'MM-2026-1002', 'Robert King', 'ACTIVE'),
      ('CLM_DEMO_1003', 'MM-2026-1003', 'Alice Brown', 'ACTIVE'),
      ('CLM_DEMO_1004', 'MM-2026-1004', 'Samuel Price', 'ACTIVE')
) s (CLAIM_ID, FILE_NUMBER, PATIENT_NAME, STATUS)
ON t.CLAIM_ID = s.CLAIM_ID
WHEN MATCHED THEN UPDATE SET
  FILE_NUMBER = s.FILE_NUMBER,
  PATIENT_NAME = s.PATIENT_NAME,
  STATUS = s.STATUS,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
  INSERT (CLAIM_ID, FILE_NUMBER, PATIENT_NAME, STATUS, CREATED_AT, UPDATED_AT)
  VALUES (s.CLAIM_ID, s.FILE_NUMBER, s.PATIENT_NAME, s.STATUS, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_DEFENDANT') t
USING (
    SELECT * FROM VALUES
      ('DEF_DEMO_1001', 'CLM_DEMO_1001', 'Dr. Ellie Green', 'Obstetrics & Gynecology', 'COMPLETE', 'Post-op hemorrhage review', 'Hemorrhage', 'Delayed intervention concern'),
      ('DEF_DEMO_1002', 'CLM_DEMO_1002', 'Dr. Noah White', 'Emergency Medicine', 'COMPLETE', 'Chest pain triage review', 'Myocardial infarction', 'Possible missed high-risk indicators'),
      ('DEF_DEMO_1003', 'CLM_DEMO_1003', 'Dr. Priya Shah', 'Internal Medicine', 'RUNNING', 'Inpatient deterioration review', 'Sepsis', 'Escalation timing concern'),
      ('DEF_DEMO_1004', 'CLM_DEMO_1004', 'Dr. Carlos Young', 'Surgery', 'PENDING', 'Peri-op complication review', 'Bowel injury', 'Informed consent scope concern')
) s (DEFENDANT_ID, CLAIM_ID, DEFENDANT_NAME, DEFENDANT_SPECIALTY, PIPELINE_STATUS, BRIEF_SYNOPSIS, ALLEGED_INJURY_TERMS, ALLEGATION_SUMMARY)
ON t.DEFENDANT_ID = s.DEFENDANT_ID
WHEN MATCHED THEN UPDATE SET
  CLAIM_ID = s.CLAIM_ID,
  DEFENDANT_NAME = s.DEFENDANT_NAME,
  DEFENDANT_SPECIALTY = s.DEFENDANT_SPECIALTY,
  PIPELINE_STATUS = s.PIPELINE_STATUS,
  BRIEF_SYNOPSIS = s.BRIEF_SYNOPSIS,
  ALLEGED_INJURY_TERMS = s.ALLEGED_INJURY_TERMS,
  ALLEGATION_SUMMARY = s.ALLEGATION_SUMMARY,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
  INSERT (DEFENDANT_ID, CLAIM_ID, DEFENDANT_NAME, DEFENDANT_SPECIALTY, PIPELINE_STATUS, BRIEF_SYNOPSIS, ALLEGED_INJURY_TERMS, ALLEGATION_SUMMARY, CREATED_AT, UPDATED_AT)
  VALUES (s.DEFENDANT_ID, s.CLAIM_ID, s.DEFENDANT_NAME, s.DEFENDANT_SPECIALTY, s.PIPELINE_STATUS, s.BRIEF_SYNOPSIS, s.ALLEGED_INJURY_TERMS, s.ALLEGATION_SUMMARY, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

-- -------------------------
-- Sample assignments/workflow/dashboard-driving data
-- -------------------------
MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_ASSIGNMENT') t
USING (
    SELECT * FROM VALUES
      ('ASG_1001', 'CLM_DEMO_1001', 'USR_FACULTY_1', 'USR_ANALYST_1', 'MEDICAL_FACULTY', 'ACTIVE', 'High', DATEADD('day', 3, CURRENT_TIMESTAMP()), DATEADD('day', -1, CURRENT_TIMESTAMP()), NULL, 'Urgent OB review'),
      ('ASG_1002', 'CLM_DEMO_1002', 'USR_FACULTY_2', 'USR_ANALYST_1', 'MEDICAL_FACULTY', 'ACTIVE', 'Medium', DATEADD('day', 5, CURRENT_TIMESTAMP()), DATEADD('day', -2, CURRENT_TIMESTAMP()), NULL, 'ER chest pain case'),
      ('ASG_1003', 'CLM_DEMO_1003', 'USR_FACULTY_1', 'USR_ANALYST_1', 'MEDICAL_FACULTY', 'COMPLETED', 'Low', DATEADD('day', 1, CURRENT_TIMESTAMP()), DATEADD('day', -7, CURRENT_TIMESTAMP()), DATEADD('day', -2, CURRENT_TIMESTAMP()), 'Returned for advice review')
) s (ASSIGNMENT_ID, CLAIM_ID, ASSIGNED_TO_USER_ID, ASSIGNED_BY_USER_ID, ASSIGNMENT_ROLE_CODE, ASSIGNMENT_STATUS, PRIORITY, DUE_AT, ASSIGNED_AT, UNASSIGNED_AT, NOTES)
ON t.ASSIGNMENT_ID = s.ASSIGNMENT_ID
WHEN MATCHED THEN UPDATE SET
  CLAIM_ID = s.CLAIM_ID,
  ASSIGNED_TO_USER_ID = s.ASSIGNED_TO_USER_ID,
  ASSIGNED_BY_USER_ID = s.ASSIGNED_BY_USER_ID,
  ASSIGNMENT_ROLE_CODE = s.ASSIGNMENT_ROLE_CODE,
  ASSIGNMENT_STATUS = s.ASSIGNMENT_STATUS,
  PRIORITY = s.PRIORITY,
  DUE_AT = s.DUE_AT,
  ASSIGNED_AT = s.ASSIGNED_AT,
  UNASSIGNED_AT = s.UNASSIGNED_AT,
  NOTES = s.NOTES,
  UPDATED_AT = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
  INSERT (ASSIGNMENT_ID, CLAIM_ID, ASSIGNED_TO_USER_ID, ASSIGNED_BY_USER_ID, ASSIGNMENT_ROLE_CODE, ASSIGNMENT_STATUS, PRIORITY, DUE_AT, ASSIGNED_AT, UNASSIGNED_AT, NOTES, CREATED_AT, UPDATED_AT)
  VALUES (s.ASSIGNMENT_ID, s.CLAIM_ID, s.ASSIGNED_TO_USER_ID, s.ASSIGNED_BY_USER_ID, s.ASSIGNMENT_ROLE_CODE, s.ASSIGNMENT_STATUS, s.PRIORITY, s.DUE_AT, s.ASSIGNED_AT, s.UNASSIGNED_AT, s.NOTES, CURRENT_TIMESTAMP(), CURRENT_TIMESTAMP());

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_WORKFLOW_EVENT') t
USING (
    SELECT * FROM VALUES
      ('WF_1001_A', 'CLM_DEMO_1001', 'DEF_DEMO_1001', 'STATUS_CHANGE', 'MFQ Generated', 'Assigned', DATEADD('day', -1, CURRENT_TIMESTAMP()), 'USR_ANALYST_1', 'Assigned to faculty', PARSE_JSON('{"channel":"ui"}')),
      ('WF_1002_A', 'CLM_DEMO_1002', 'DEF_DEMO_1002', 'STATUS_CHANGE', 'MFQ Generated', 'Assigned', DATEADD('day', -2, CURRENT_TIMESTAMP()), 'USR_ANALYST_1', 'Assigned to faculty', PARSE_JSON('{"channel":"ui"}')),
      ('WF_1003_A', 'CLM_DEMO_1003', 'DEF_DEMO_1003', 'STATUS_CHANGE', 'Assigned', 'Approved', DATEADD('day', -2, CURRENT_TIMESTAMP()), 'USR_FACULTY_1', 'Approved after review', PARSE_JSON('{"channel":"ui"}')),
      ('WF_1004_A', 'CLM_DEMO_1004', 'DEF_DEMO_1004', 'STATUS_CHANGE', 'Assigned', 'Rejected', DATEADD('day', -1, CURRENT_TIMESTAMP()), 'USR_FACULTY_2', 'Insufficient records', PARSE_JSON('{"channel":"ui"}'))
) s (WORKFLOW_EVENT_ID, CLAIM_ID, DEFENDANT_ID, EVENT_TYPE, FROM_STATUS, TO_STATUS, EVENT_TS, EVENT_BY_USER_ID, EVENT_NOTE, EVENT_METADATA)
ON t.WORKFLOW_EVENT_ID = s.WORKFLOW_EVENT_ID
WHEN MATCHED THEN UPDATE SET
  CLAIM_ID = s.CLAIM_ID,
  DEFENDANT_ID = s.DEFENDANT_ID,
  EVENT_TYPE = s.EVENT_TYPE,
  FROM_STATUS = s.FROM_STATUS,
  TO_STATUS = s.TO_STATUS,
  EVENT_TS = s.EVENT_TS,
  EVENT_BY_USER_ID = s.EVENT_BY_USER_ID,
  EVENT_NOTE = s.EVENT_NOTE,
  EVENT_METADATA = s.EVENT_METADATA
WHEN NOT MATCHED THEN
  INSERT (WORKFLOW_EVENT_ID, CLAIM_ID, DEFENDANT_ID, EVENT_TYPE, FROM_STATUS, TO_STATUS, EVENT_TS, EVENT_BY_USER_ID, EVENT_NOTE, EVENT_METADATA)
  VALUES (s.WORKFLOW_EVENT_ID, s.CLAIM_ID, s.DEFENDANT_ID, s.EVENT_TYPE, s.FROM_STATUS, s.TO_STATUS, s.EVENT_TS, s.EVENT_BY_USER_ID, s.EVENT_NOTE, s.EVENT_METADATA);

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_SECTION_ASSIGNMENT') t
USING (
  SELECT
    'SASG_1001' AS SECTION_ASSIGNMENT_ID,
    'CLM_DEMO_1001' AS CLAIM_ID,
    (SELECT SECTION_ID FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.QST_SECTION') WHERE FORM_KEY='MFQ_V1' AND SECTION_KEY='SEC_I' QUALIFY ROW_NUMBER() OVER (ORDER BY CREATED_AT DESC) = 1) AS SECTION_ID,
    'USR_FACULTY_1' AS ASSIGNED_TO_USER_ID,
    'USR_ANALYST_1' AS ASSIGNED_BY_USER_ID,
    'ACTIVE' AS ASSIGNMENT_STATUS,
    DATEADD('hour', -16, CURRENT_TIMESTAMP()) AS ASSIGNED_AT,
    NULL::TIMESTAMP_LTZ AS COMPLETED_AT,
    'Complete section I first' AS NOTES
  UNION ALL
  SELECT
    'SASG_1002',
    'CLM_DEMO_1002',
    (SELECT SECTION_ID FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.QST_SECTION') WHERE FORM_KEY='MFQ_V1' AND SECTION_KEY='SEC_COVER' QUALIFY ROW_NUMBER() OVER (ORDER BY CREATED_AT DESC) = 1),
    'USR_FACULTY_2',
    'USR_ANALYST_1',
    'ACTIVE',
    DATEADD('hour', -28, CURRENT_TIMESTAMP()),
    NULL::TIMESTAMP_LTZ,
    'Confirm demographics'
) s
ON t.SECTION_ASSIGNMENT_ID = s.SECTION_ASSIGNMENT_ID
WHEN MATCHED THEN UPDATE SET
  CLAIM_ID = s.CLAIM_ID,
  SECTION_ID = s.SECTION_ID,
  ASSIGNED_TO_USER_ID = s.ASSIGNED_TO_USER_ID,
  ASSIGNED_BY_USER_ID = s.ASSIGNED_BY_USER_ID,
  ASSIGNMENT_STATUS = s.ASSIGNMENT_STATUS,
  ASSIGNED_AT = s.ASSIGNED_AT,
  COMPLETED_AT = s.COMPLETED_AT,
  NOTES = s.NOTES
WHEN NOT MATCHED THEN
  INSERT (SECTION_ASSIGNMENT_ID, CLAIM_ID, SECTION_ID, ASSIGNED_TO_USER_ID, ASSIGNED_BY_USER_ID, ASSIGNMENT_STATUS, ASSIGNED_AT, COMPLETED_AT, NOTES)
  VALUES (s.SECTION_ASSIGNMENT_ID, s.CLAIM_ID, s.SECTION_ID, s.ASSIGNED_TO_USER_ID, s.ASSIGNED_BY_USER_ID, s.ASSIGNMENT_STATUS, s.ASSIGNED_AT, s.COMPLETED_AT, s.NOTES);

-- -------------------------
-- Sample questionnaires answers (existing core MFQ_ANSWER)
-- -------------------------
MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MFQ_ANSWER') t
USING (
    SELECT * FROM VALUES
      ('ANS_DEMO_1', 'RUN_DEMO_1', 'DEF_DEMO_1001', 'COVER_PATIENT_NAME', 'Jane Doe', 'Jane Doe', 1, TRUE, 'GENERATED', 0.97),
      ('ANS_DEMO_2', 'RUN_DEMO_1', 'DEF_DEMO_1001', 'S1_Q1', 'YES', 'YES', 1, TRUE, 'GENERATED', 0.93),
      ('ANS_DEMO_3', 'RUN_DEMO_2', 'DEF_DEMO_1002', 'COVER_PATIENT_NAME', 'Robert King', 'Robert King', 1, TRUE, 'GENERATED', 0.95),
      ('ANS_DEMO_4', 'RUN_DEMO_2', 'DEF_DEMO_1002', 'S1_Q1', 'NO', 'NO', 1, TRUE, 'GENERATED', 0.90)
) s (ANSWER_ID, RUN_ID, DEFENDANT_ID, QUESTION_KEY, ANSWER_RAW, ANSWER_TEXT, ANSWER_VERSION, IS_CURRENT, STATUS, CONFIDENCE_SCORE)
ON t.ANSWER_ID = s.ANSWER_ID
WHEN MATCHED THEN UPDATE SET
  RUN_ID = s.RUN_ID,
  DEFENDANT_ID = s.DEFENDANT_ID,
  QUESTION_KEY = s.QUESTION_KEY,
  ANSWER_RAW = s.ANSWER_RAW,
  ANSWER_TEXT = s.ANSWER_TEXT,
  ANSWER_VERSION = s.ANSWER_VERSION,
  IS_CURRENT = s.IS_CURRENT,
  STATUS = s.STATUS,
  CONFIDENCE_SCORE = s.CONFIDENCE_SCORE
WHEN NOT MATCHED THEN
  INSERT (ANSWER_ID, RUN_ID, DEFENDANT_ID, QUESTION_ID, QUESTION_KEY, ANSWER_VERSION, IS_CURRENT, ANSWER_RAW, ANSWER_TEXT, STATUS, CONFIDENCE_SCORE, CREATED_AT)
  SELECT
    s.ANSWER_ID,
    s.RUN_ID,
    s.DEFENDANT_ID,
    q.QUESTION_ID,
    s.QUESTION_KEY,
    s.ANSWER_VERSION,
    s.IS_CURRENT,
    s.ANSWER_RAW,
    s.ANSWER_TEXT,
    s.STATUS,
    s.CONFIDENCE_SCORE,
    CURRENT_TIMESTAMP()
  FROM IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.QST_QUESTION') q
  WHERE q.FORM_KEY = 'MFQ_V1'
    AND q.QUESTION_KEY = s.QUESTION_KEY
    AND q.IS_CURRENT = TRUE
  QUALIFY ROW_NUMBER() OVER (PARTITION BY q.QUESTION_KEY ORDER BY q.CREATED_AT DESC) = 1;

-- -------------------------
-- Notifications, missing docs, audit/outbox
-- -------------------------
MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.NOTIFICATION_EVENT') t
USING (
    SELECT * FROM VALUES
      ('NTF_1001', 'USR_FACULTY_1', 'ASSIGNMENT_CREATED', 'New assignment received', 'Claim CLM_DEMO_1001 assigned to you', 'CLM_DEMO_1001', 'HIGH', FALSE, '/claims/CLM_DEMO_1001', DATEADD('hour', -3, CURRENT_TIMESTAMP()), NULL, PARSE_JSON('{"assignment_id":"ASG_1001"}')),
      ('NTF_1002', 'USR_ANALYST_1', 'MFQ_APPROVED', 'MFQ approved', 'Claim CLM_DEMO_1003 approved by Medical Faculty', 'CLM_DEMO_1003', 'INFO', FALSE, '/claims/CLM_DEMO_1003', DATEADD('hour', -6, CURRENT_TIMESTAMP()), NULL, PARSE_JSON('{"workflow_event_id":"WF_1003_A"}')),
      ('NTF_1003', 'USR_FACULTY_2', 'MISSING_DOC_REQUEST', 'Additional documents requested', 'Please review missing document request for CLM_DEMO_1004', 'CLM_DEMO_1004', 'MEDIUM', FALSE, '/claims/CLM_DEMO_1004', DATEADD('hour', -2, CURRENT_TIMESTAMP()), NULL, PARSE_JSON('{"request_id":"MDR_1001"}'))
) s (NOTIFICATION_ID, USER_ID, EVENT_TYPE, EVENT_TITLE, EVENT_MESSAGE, CLAIM_ID, EVENT_PRIORITY, IS_READ, ACTION_URL, EVENT_TS, EXPIRES_AT, PAYLOAD)
ON t.NOTIFICATION_ID = s.NOTIFICATION_ID
WHEN MATCHED THEN UPDATE SET
  USER_ID = s.USER_ID,
  EVENT_TYPE = s.EVENT_TYPE,
  EVENT_TITLE = s.EVENT_TITLE,
  EVENT_MESSAGE = s.EVENT_MESSAGE,
  CLAIM_ID = s.CLAIM_ID,
  EVENT_PRIORITY = s.EVENT_PRIORITY,
  IS_READ = s.IS_READ,
  ACTION_URL = s.ACTION_URL,
  EVENT_TS = s.EVENT_TS,
  EXPIRES_AT = s.EXPIRES_AT,
  PAYLOAD = s.PAYLOAD
WHEN NOT MATCHED THEN
  INSERT (NOTIFICATION_ID, USER_ID, EVENT_TYPE, EVENT_TITLE, EVENT_MESSAGE, CLAIM_ID, EVENT_PRIORITY, IS_READ, ACTION_URL, EVENT_TS, EXPIRES_AT, PAYLOAD)
  VALUES (s.NOTIFICATION_ID, s.USER_ID, s.EVENT_TYPE, s.EVENT_TITLE, s.EVENT_MESSAGE, s.CLAIM_ID, s.EVENT_PRIORITY, s.IS_READ, s.ACTION_URL, s.EVENT_TS, s.EXPIRES_AT, s.PAYLOAD);

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.NOTIFICATION_READ_STATUS') t
USING (
    SELECT * FROM VALUES
      ('NRS_1001', 'NTF_1002', 'USR_ANALYST_1', DATEADD('hour', -1, CURRENT_TIMESTAMP()), NULL)
) s (READ_STATUS_ID, NOTIFICATION_ID, USER_ID, READ_AT, DISMISSED_AT)
ON t.READ_STATUS_ID = s.READ_STATUS_ID
WHEN MATCHED THEN UPDATE SET
  NOTIFICATION_ID = s.NOTIFICATION_ID,
  USER_ID = s.USER_ID,
  READ_AT = s.READ_AT,
  DISMISSED_AT = s.DISMISSED_AT
WHEN NOT MATCHED THEN
  INSERT (READ_STATUS_ID, NOTIFICATION_ID, USER_ID, READ_AT, DISMISSED_AT)
  VALUES (s.READ_STATUS_ID, s.NOTIFICATION_ID, s.USER_ID, s.READ_AT, s.DISMISSED_AT);

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.MISSING_DOCUMENT_REQUEST') t
USING (
    SELECT * FROM VALUES
      ('MDR_1001', 'CLM_DEMO_1004', 'DEF_DEMO_1004', 'USR_FACULTY_2', 'MISSING_DOCUMENT', 'OPEN', 'Operative report missing signature page', 'Operative Report', '2025-01-01 to 2025-01-31', DATEADD('day', -1, CURRENT_TIMESTAMP()), NULL, NULL)
) s (REQUEST_ID, CLAIM_ID, DEFENDANT_ID, REQUESTED_BY_USER_ID, REQUEST_TYPE, REQUEST_STATUS, REQUEST_REASON, REQUESTED_DOC_TYPE, REQUESTED_DOC_DATE_RANGE, REQUESTED_AT, RESOLVED_AT, RESOLUTION_NOTE)
ON t.REQUEST_ID = s.REQUEST_ID
WHEN MATCHED THEN UPDATE SET
  CLAIM_ID = s.CLAIM_ID,
  DEFENDANT_ID = s.DEFENDANT_ID,
  REQUESTED_BY_USER_ID = s.REQUESTED_BY_USER_ID,
  REQUEST_TYPE = s.REQUEST_TYPE,
  REQUEST_STATUS = s.REQUEST_STATUS,
  REQUEST_REASON = s.REQUEST_REASON,
  REQUESTED_DOC_TYPE = s.REQUESTED_DOC_TYPE,
  REQUESTED_DOC_DATE_RANGE = s.REQUESTED_DOC_DATE_RANGE,
  REQUESTED_AT = s.REQUESTED_AT,
  RESOLVED_AT = s.RESOLVED_AT,
  RESOLUTION_NOTE = s.RESOLUTION_NOTE
WHEN NOT MATCHED THEN
  INSERT (REQUEST_ID, CLAIM_ID, DEFENDANT_ID, REQUESTED_BY_USER_ID, REQUEST_TYPE, REQUEST_STATUS, REQUEST_REASON, REQUESTED_DOC_TYPE, REQUESTED_DOC_DATE_RANGE, REQUESTED_AT, RESOLVED_AT, RESOLUTION_NOTE)
  VALUES (s.REQUEST_ID, s.CLAIM_ID, s.DEFENDANT_ID, s.REQUESTED_BY_USER_ID, s.REQUEST_TYPE, s.REQUEST_STATUS, s.REQUEST_REASON, s.REQUESTED_DOC_TYPE, s.REQUESTED_DOC_DATE_RANGE, s.REQUESTED_AT, s.RESOLVED_AT, s.RESOLUTION_NOTE);

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APPIAN_OUTBOX_EVENT') t
USING (
    SELECT * FROM VALUES
      ('OUTBOX_1001', 'CLAIM', 'CLM_DEMO_1003', 'CLAIM_STATUS_CHANGED', PARSE_JSON('{"claim_id":"CLM_DEMO_1003","status":"Approved"}'), 'PENDING', 0, NULL, NULL, NULL)
) s (OUTBOX_EVENT_ID, ENTITY_TYPE, ENTITY_ID, EVENT_TYPE, EVENT_PAYLOAD, DELIVERY_STATUS, RETRY_COUNT, LAST_ATTEMPT_AT, DELIVERED_AT, ERROR_MESSAGE)
ON t.OUTBOX_EVENT_ID = s.OUTBOX_EVENT_ID
WHEN MATCHED THEN UPDATE SET
  ENTITY_TYPE = s.ENTITY_TYPE,
  ENTITY_ID = s.ENTITY_ID,
  EVENT_TYPE = s.EVENT_TYPE,
  EVENT_PAYLOAD = s.EVENT_PAYLOAD,
  DELIVERY_STATUS = s.DELIVERY_STATUS,
  RETRY_COUNT = s.RETRY_COUNT,
  LAST_ATTEMPT_AT = s.LAST_ATTEMPT_AT,
  DELIVERED_AT = s.DELIVERED_AT,
  ERROR_MESSAGE = s.ERROR_MESSAGE
WHEN NOT MATCHED THEN
  INSERT (OUTBOX_EVENT_ID, ENTITY_TYPE, ENTITY_ID, EVENT_TYPE, EVENT_PAYLOAD, DELIVERY_STATUS, RETRY_COUNT, LAST_ATTEMPT_AT, DELIVERED_AT, ERROR_MESSAGE, CREATED_AT)
  VALUES (s.OUTBOX_EVENT_ID, s.ENTITY_TYPE, s.ENTITY_ID, s.EVENT_TYPE, s.EVENT_PAYLOAD, s.DELIVERY_STATUS, s.RETRY_COUNT, s.LAST_ATTEMPT_AT, s.DELIVERED_AT, s.ERROR_MESSAGE, CURRENT_TIMESTAMP());

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.APP_AUDIT_LOG') t
USING (
    SELECT * FROM VALUES
      ('AUD_1001', 'CLAIM_ASSIGNMENT', 'ASG_1001', 'CREATE', DATEADD('hour', -20, CURRENT_TIMESTAMP()), 'USR_ANALYST_1', NULL, PARSE_JSON('{"claim_id":"CLM_DEMO_1001","assigned_to":"USR_FACULTY_1"}'), 'req-demo-1001', 'UI'),
      ('AUD_1002', 'WORKFLOW_EVENT', 'WF_1003_A', 'STATUS_CHANGE', DATEADD('hour', -10, CURRENT_TIMESTAMP()), 'USR_FACULTY_1', PARSE_JSON('{"status":"Assigned"}'), PARSE_JSON('{"status":"Approved"}'), 'req-demo-1002', 'UI')
) s (AUDIT_ID, ENTITY_TYPE, ENTITY_ID, ACTION_TYPE, ACTION_TS, ACTOR_USER_ID, BEFORE_STATE, AFTER_STATE, REQUEST_ID, SOURCE_CHANNEL)
ON t.AUDIT_ID = s.AUDIT_ID
WHEN MATCHED THEN UPDATE SET
  ENTITY_TYPE = s.ENTITY_TYPE,
  ENTITY_ID = s.ENTITY_ID,
  ACTION_TYPE = s.ACTION_TYPE,
  ACTION_TS = s.ACTION_TS,
  ACTOR_USER_ID = s.ACTOR_USER_ID,
  BEFORE_STATE = s.BEFORE_STATE,
  AFTER_STATE = s.AFTER_STATE,
  REQUEST_ID = s.REQUEST_ID,
  SOURCE_CHANNEL = s.SOURCE_CHANNEL
WHEN NOT MATCHED THEN
  INSERT (AUDIT_ID, ENTITY_TYPE, ENTITY_ID, ACTION_TYPE, ACTION_TS, ACTOR_USER_ID, BEFORE_STATE, AFTER_STATE, REQUEST_ID, SOURCE_CHANNEL)
  VALUES (s.AUDIT_ID, s.ENTITY_TYPE, s.ENTITY_ID, s.ACTION_TYPE, s.ACTION_TS, s.ACTOR_USER_ID, s.BEFORE_STATE, s.AFTER_STATE, s.REQUEST_ID, s.SOURCE_CHANNEL);

MERGE INTO IDENTIFIER($APP_DB || '.' || $APP_SCHEMA || '.CLAIM_DOCUMENT') t
USING (
    SELECT * FROM VALUES
      ('DOC_1001', 'CLM_DEMO_1001', 'DEF_DEMO_1001', 'CLM_DEMO_1001_ED_RECORDS.pdf', 'ED Records', 'Clinical', '@mfq_stage/docs/CLM_DEMO_1001_ED_RECORDS.pdf', 'DEMO', TO_DATE('2025-02-14'), 241328, 'application/pdf', 'COMPLETE'),
      ('DOC_1002', 'CLM_DEMO_1004', 'DEF_DEMO_1004', 'CLM_DEMO_1004_OP_NOTE.pdf', 'Operative Report', 'Surgery', '@mfq_stage/docs/CLM_DEMO_1004_OP_NOTE.pdf', 'DEMO', TO_DATE('2025-01-12'), 138091, 'application/pdf', 'COMPLETE')
) s (CLAIM_DOCUMENT_ID, CLAIM_ID, DEFENDANT_ID, FILE_NAME, DOC_TYPE, DOC_SUBTYPE, STORAGE_PATH, SOURCE_SYSTEM, DOCUMENT_DATE, FILE_SIZE_BYTES, MIME_TYPE, OCR_STATUS)
ON t.CLAIM_DOCUMENT_ID = s.CLAIM_DOCUMENT_ID
WHEN MATCHED THEN UPDATE SET
  CLAIM_ID = s.CLAIM_ID,
  DEFENDANT_ID = s.DEFENDANT_ID,
  FILE_NAME = s.FILE_NAME,
  DOC_TYPE = s.DOC_TYPE,
  DOC_SUBTYPE = s.DOC_SUBTYPE,
  STORAGE_PATH = s.STORAGE_PATH,
  SOURCE_SYSTEM = s.SOURCE_SYSTEM,
  DOCUMENT_DATE = s.DOCUMENT_DATE,
  FILE_SIZE_BYTES = s.FILE_SIZE_BYTES,
  MIME_TYPE = s.MIME_TYPE,
  OCR_STATUS = s.OCR_STATUS
WHEN NOT MATCHED THEN
  INSERT (CLAIM_DOCUMENT_ID, CLAIM_ID, DEFENDANT_ID, FILE_NAME, DOC_TYPE, DOC_SUBTYPE, STORAGE_PATH, SOURCE_SYSTEM, DOCUMENT_DATE, FILE_SIZE_BYTES, MIME_TYPE, OCR_STATUS, CREATED_AT)
  VALUES (s.CLAIM_DOCUMENT_ID, s.CLAIM_ID, s.DEFENDANT_ID, s.FILE_NAME, s.DOC_TYPE, s.DOC_SUBTYPE, s.STORAGE_PATH, s.SOURCE_SYSTEM, s.DOCUMENT_DATE, s.FILE_SIZE_BYTES, s.MIME_TYPE, s.OCR_STATUS, CURRENT_TIMESTAMP());
-- Demo seed for enterprise prototype walkthrough.

INSERT INTO MFQ_APP_USERS (USERNAME, APP_ROLE, IS_ACTIVE)
SELECT 'ANALYST_1', 'Claims Analyst', TRUE UNION ALL
SELECT 'ADVICE_1', 'Advice Team', TRUE UNION ALL
SELECT 'FACULTY_1', 'Medical Faculty', TRUE UNION ALL
SELECT 'EXEC_1', 'Executive', TRUE UNION ALL
SELECT 'ADMIN_1', 'Admin', TRUE;

INSERT INTO MFQ_ROLE_PAGE_ACCESS (APP_ROLE, PAGE_KEY, IS_ALLOWED)
SELECT 'Claims Analyst', 'Dashboard', TRUE UNION ALL
SELECT 'Claims Analyst', 'Claims', TRUE UNION ALL
SELECT 'Claims Analyst', 'Claim Details', TRUE UNION ALL
SELECT 'Claims Analyst', 'Reports', TRUE UNION ALL
SELECT 'Advice Team', 'Dashboard', TRUE UNION ALL
SELECT 'Advice Team', 'Claims', TRUE UNION ALL
SELECT 'Medical Faculty', 'Dashboard', TRUE UNION ALL
SELECT 'Medical Faculty', 'Claims', TRUE UNION ALL
SELECT 'Medical Faculty', 'Claim Details', TRUE UNION ALL
SELECT 'Executive', 'Dashboard', TRUE UNION ALL
SELECT 'Executive', 'Reports', TRUE UNION ALL
SELECT 'Admin', 'Admin', TRUE;

INSERT INTO MFQ_ASSIGNMENT_RULES (RULE_ID, SPECIALTY, DEFAULT_FACULTY, IS_ACTIVE)
SELECT 'R-OB-1', 'OB/GYN', 'FACULTY_1', TRUE UNION ALL
SELECT 'R-ER-1', 'Emergency Medicine', 'FACULTY_2', TRUE UNION ALL
SELECT 'R-IM-1', 'Internal Medicine', 'FACULTY_3', TRUE;

INSERT INTO MFQ_NOTIFICATIONS (NOTIFICATION_ID, TARGET_USER, TITLE, MESSAGE, SEVERITY, IS_READ)
SELECT UUID_STRING(), 'ALL', 'Daily Queue Refresh', 'Claim queue has been refreshed from workflow pipeline.', 'info', FALSE UNION ALL
SELECT UUID_STRING(), 'ANALYST_1', 'Missing Document Alert', 'Claim C-10014 requires additional operative notes.', 'warning', FALSE UNION ALL
SELECT UUID_STRING(), 'FACULTY_1', 'Assignment Received', 'New section assignment waiting for review.', 'success', FALSE UNION ALL
SELECT UUID_STRING(), 'ADMIN_1', 'RBAC Change Audit', 'Two page-access mappings changed in the last 24 hours.', 'info', FALSE;
